(ns status-im.react-native.resources)

(def ui
  {:empty-hashtags      (js/require "./resources/images/ui/empty-hashtags.png")
   :empty-recent        (js/require "./resources/images/ui/empty-recent.png")
   :analytics-image     (js/require "./resources/images/ui/analytics-image.png")
   :welcome-image       (js/require "./resources/images/ui/welcome-image.png")
   :lock                (js/require "./resources/images/ui/lock.png")
   :tribute-to-talk     (js/require "./resources/images/ui/tribute-to-talk.png")
   :wallet-welcome      (js/require "./resources/images/ui/wallet-welcome.png")
   :hardwallet-card     (js/require "./resources/images/ui/hardwallet-card.png")
   :secret-keys         (js/require "./resources/images/ui/secret-keys.png")
   :keycard-lock        (js/require "./resources/images/ui/keycard-lock.png")
   :hold-card-animation (try (js/require "./resources/images/ui/hold-card-animation.gif")
                             (catch :default e))
   :warning-sign        (js/require "./resources/images/ui/warning-sign.png")
   :phone-nfc-on        (js/require "./resources/images/ui/phone-nfc-on.png")
   :phone-nfc-off       (js/require "./resources/images/ui/phone-nfc-off.png")
   :dapp-store          (js/require "./resources/images/ui/dapp-store.png")
   :small-badge         (js/require "./resources/images/ui/small-badge.png")
   :large-badge         (js/require "./resources/images/ui/large-badge.png")})
