(ns status-im.react-native.resources)

(def contacts
  {:mkr-market         (js/require "./resources/images/contacts/mkr-market.png")
   :oaken-water-meter  (js/require "./resources/images/contacts/oaken-water-meter.png")
   :gnosis             (js/require "./resources/images/contacts/gnosis.png")
   :melonport          (js/require "./resources/images/contacts/melonport.png")
   :bchat              (js/require "./resources/images/contacts/bchat.png")
   :dentacoin          (js/require "./resources/images/contacts/Dentacoin.png")
   :augur              (js/require "./resources/images/contacts/augur.png")
   :ethlance           (js/require "./resources/images/contacts/ethlance.png")
   :commiteth          (js/require "./resources/images/contacts/commiteth.png")
   :etherplay          (js/require "./resources/images/contacts/etherplay.png")
   :ethcro             (js/require "./resources/images/contacts/ethcro.png")
   :easytrade          (js/require "./resources/images/contacts/easytrade.png")
   :nuo                (js/require "./resources/images/contacts/nuo.png")

   :dragonereum        (js/require "./resources/images/contacts/dragonereum.png")
   :name-bazaar        (js/require "./resources/images/contacts/name-bazaar.png")
   :cryptographics     (js/require "./resources/images/contacts/cryptographics.png")
   :cryptopunks        (js/require "./resources/images/contacts/cryptopunks.png")
   :cryptotakeovers    (js/require "./resources/images/contacts/cryptotakeovers.png")
   :cryptokitties      (js/require "./resources/images/contacts/cryptokitties.png")
   :decentraland       (js/require "./resources/images/contacts/decentraland.png")
   :etheremon          (js/require "./resources/images/contacts/etheremon.png")
   :cryptostrikers     (js/require "./resources/images/contacts/cryptostrikers.png")
   :oasis-direct       (js/require "./resources/images/contacts/oasis-direct.png")
   :erc-dex            (js/require "./resources/images/contacts/erc-dex.png")
   :cent               (js/require "./resources/images/contacts/cent.png")
   :kickback           (js/require "./resources/images/contacts/kickback.png")
   :hexel              (js/require "./resources/images/contacts/hexel.png")
   :peepeth            (js/require "./resources/images/contacts/peepeth.png")
   :etherbots          (js/require "./resources/images/contacts/etherbots.png")
   :opensea            (js/require "./resources/images/contacts/opensea.png")
   :kyber              (js/require "./resources/images/contacts/kyber.png")
   :bancor             (js/require "./resources/images/contacts/bancor.png")
   :blockimmo          (js/require "./resources/images/contacts/blockimmo.png")
   :cryptocribs        (js/require "./resources/images/contacts/cryptocribs.png")
   :cryptofighters     (js/require "./resources/images/contacts/cryptofighters.png")
   :etherman           (js/require "./resources/images/contacts/etherman.png")
   :airswap            (js/require "./resources/images/contacts/airswap.png")
   :civitas            (js/require "./resources/images/contacts/civitas.png")
   :dai                (js/require "./resources/images/contacts/dai.png")
   :local-ethereum     (js/require "./resources/images/contacts/local-ethereum.png")
   :eth2phone          (js/require "./resources/images/contacts/eth2phone.png")
   :bounties-network   (js/require "./resources/images/contacts/bounties-network.png")
   :cryptopurr         (js/require "./resources/images/contacts/cryptopurr.png")
   :ethlend            (js/require "./resources/images/contacts/ethlend.png")
   :smartz             (js/require "./resources/images/contacts/smartz.png")
   :snt-voting         (js/require "./resources/images/contacts/snt-voting.png")
   :superrare          (js/require "./resources/images/contacts/superrare.png")
   :3box               (js/require "./resources/images/contacts/3Box.png")
   :aragon             (js/require "./resources/images/contacts/aragon.png")
   :slowtrade          (js/require "./resources/images/contacts/slowtrade.png")

   :ddex               (js/require "./resources/images/contacts/ddex.png")
   :emoon              (js/require "./resources/images/contacts/emoon.png")
   :livepeer           (js/require "./resources/images/contacts/livepeer.png")

   :console            (js/require "./resources/images/contacts/console.png")})

(def ui
  {:empty-hashtags      (js/require "./resources/images/ui/empty-hashtags.png")
   :empty-recent        (js/require "./resources/images/ui/empty-recent.png")
   :analytics-image     (js/require "./resources/images/ui/analytics-image.png")
   :welcome-image       (js/require "./resources/images/ui/welcome-image.png")
   :lock                (js/require "./resources/images/ui/lock.png")
   :tribute-to-talk     (js/require "./resources/images/ui/tribute-to-talk.png")
   :wallet-welcome      (js/require "./resources/images/ui/wallet-welcome.png")
   :hardwallet-card     (js/require "./resources/images/ui/hardwallet-card.png")
   :secret-keys         (js/require "./resources/images/ui/secret-keys.png")
   :keycard-lock        (js/require "./resources/images/ui/keycard-lock.png")
   :hold-card-animation (js/require "./resources/images/ui/hold-card-animation.png")
   :warning-sign        (js/require "./resources/images/ui/warning-sign.png")
   :phone-nfc-on        (js/require "./resources/images/ui/phone-nfc-on.png")
   :phone-nfc-off       (js/require "./resources/images/ui/phone-nfc-off.png")
   :dapp-store          (js/require "./resources/images/ui/dapp-store.png")})
