_extends: probot-settings

project-board:
  name: 'Pipeline for QA'
  tested-pr-label-name: 'Tested - Issues'
  contributor-column-name: 'CONTRIBUTOR'
  review-column-name: 'REVIEW'
  test-column-name: 'TO TEST'

automated-tests:
  repo-full-name: 'status-im/status-react'
  job-full-name: 'end-to-end-tests/status-app-end-to-end-tests'

github-team:
  slug: 'clojure'

prchecklist:
  title: Pull Request Checklist
  checklist:
    - 'Have you updated the documentation, if impacted (e.g. [docs.status.im](https://docs.status.im/docs/build_status.html))?'
