var TopLevel = {
  "abs" : function () {},
  "ActionSheetIOS" : function () {},
  "add" : function () {},
  "addEventListener" : function () {},
  "addListener" : function () {},
  "addPeer" : function () {},
  "addSymKey" : function () {},
  "addTier2Support" : function () {},
  "Alert" : function () {},
  "alert" : function () {},
  "all" : function () {},
  "Android" : function () {},
  "android" : function () {},
  "Animated" : function () {},
  "append" : function () {},
  "appStateChange" : function () {},
  "args" : function () {},
  "argv" : function () {},
  "Array" : function () {},
  "array" : function () {},
  "AsyncStorage" : function () {},
  "at" : function () {},
  "back" : function () {},
  "BACK" : function () {},
  "BackHandler" : function () {},
  "balanceOf" : function () {},
  "bezier" : function () {},
  "BigNumber" : function () {},
  "blur" : function () {},
  "button" : function () {},
  "bytesToHex" : function () {},
  "call" : function () {},
  "callPrivateRPC" : function () {},
  "callRPC" : function () {},
  "canImplyAuthentication" : function () {},
  "catch" : function () {},
  "Chance" : function () {},
  "changePin" : function () {},
  "Channel" : function () {},
  "chaosModeUpdate" : function () {},
  "charCodeAt" : function () {},
  "checkAddressChecksum" : function () {},
  "checkVideoAuthorizationStatus" : function () {},
  "author": function() {},
  "encryptionId": function() {},
  "chat": function() {},
  "messageId": function() {},
  "clear" : function () {},
  "clearCookies" : function () {},
  "clearInterval" : function () {},
  "clearStorageAPIs" : function () {},
  "clearTimeout" : function () {},
  "Clipboard" : function () {},
  "close" : function () {},
  "closeApplication" : function () {},
  "code" : function () {},
  "concat" : function () {},
  "confirmMessagesProcessed" : function () {},
  "chats": function() {},
  "rawMessages": function() {},
  "messages": function() {},
  "discovery": function() {},
  "dismiss": function() {},
  "negotiated": function() {},
  "chatId": function() {},
  "confirmMessagesProcessedByID" : function () {},
  "connectionChange" : function () {},
  "console" : function () {},
  "contacts": function () {},
  "ContactRequest" : function () {},
  "ContactRequestConfirmed" : function () {},
  "ContactRequestConfirmedHandler" : function () {},
  "ContactRequestHandler" : function () {},
  "ContactUpdate" : function () {},
  "ContactUpdateHandler" : function () {},
  "contentOffset" : function () {},
  "contentSize" : function () {},
  "contract" : function () {},
  "createAccount" : function () {},
  "createBatch" : function () {},
  "createChannel" : function () {},
  "cubic" : function () {},
  "CURRENCY" : function () {},
  "data" : function () {},
  "Date" : function () {},
  "DateTimeFormat" : function () {},
  "DEBUG" : function () {},
  "decay" : function () {},

  "dedupId": function() {},
  "DECIMAL_SEP" : function () {},
  "GROUP_SEP" : function () {},
  "PERCENT" : function () {},
  "ZERO_DIGIT" : function () {},
  "PLUS_SIGN" : function () {},
  "MINUS_SIGN" : function () {},
  "EXP_SYMBOL" : function () {},
  "PERMILL" : function () {},
  "INFINITY" : function () {},
  "NAN" : function () {},
  "DECIMAL_PATTERN" : function () {},
  "SCIENTIFIC_PATTERN" : function () {},
  "PERCENT_PATTERN" : function () {},
  "CURRENCY_PATTERN" : function () {},
  "DEF_CURRENCY_CODE" : function () {},
  "decimals" : function () {},
  "decodeURI" : function () {},
  "default" : function () {},
  "defaultAccount" : function () {},
  "defaultSeparator" : function () {},
  "delay" : function () {},
  "DesktopNotification" : function () {},
  "DeviceEventEmitter" : function () {},
  "Dimensions" : function () {},
  "dispatch" : function () {},
  "disableNotifications" : function () {},
  "displayNotification" : function () {},
  "dividedBy" : function () {},
  "DocumentDirectoryPath" : function () {},
  "dx" : function () {},
  "dy" : function () {},
  "ease" : function () {},
  "Easing" : function () {},
  "enableNotifications" : function () {},
  "enableVibration" : function () {},
  "encode" : function () {},
  "encodeURIComponent" : function () {},
  "encryptionKey" : function () {},
  "end" : function () {},
  "endCoordinates" : function () {},
  "entries" : function () {},
  "eq" : function () {},
  "Error" : function () {},
  "error" : function () {},
  "ErrorUtils" : function () {},
  "estimateGas" : function () {},
  "eth" : function () {},
  "event" : function () {},
  "EventEmmiter" : function () {},
  "exec" : function () {},
  "execute" : function () {},
  "exists" : function () {},
  "exportKeyWithPath" : function () {},
  "extPost" : function () {},
  "extractGroupMembershipSignatures" : function () {},
  "identicon": function() {},
  "identiconAsync": function() {},
  "installations": function() {},
  "generateAlias": function() {},
  "generateAliasAsync": function() {},
  "generateAliasAndIdenticonAsync": function() {},
  "fallbacks" : function () {},
  "fetch" : function () {},
  "floor" : function () {},
  "focus" : function () {},
  "format" : function () {},
  "FormData" : function () {},
  "from" : function () {},
  "fromCharCode" : function () {},
  "fromWei" : function () {},
  "generateAndLoadKey" : function () {},
  "generateMnemonic" : function () {},
  "generateSymKeyFromPassword" : function () {},
  "get" : function () {},
  "getApplicationInfo" : function () {},
  "getBalance" : function () {},
  "getBlock" : function () {},
  "getBlockNumber" : function () {},
  "getConnectionInfo" : function () {},
  "getDomain" : function () {},
  "getGasPrice" : function () {},
  "getGenericPassword" : function () {},
  "getGlobalHandler" : function () {},
  "getInitialNotification" : function () {},
  "getInitialURL" : function () {},
  "getInternetCredentials" : function () {},
  "getItem" : function () {},
  "getKeys" : function () {},
  "getLayout" : function () {},
  "getNetwork" : function () {},
  "getNode" : function () {},
  "getNodesFromContract" : function () {},
  "getPublicKey" : function () {},
  "publicKey": function() {},
  "alias": function() {},
  "getSecurityLevel" : function () {},
  "getStateForAction" : function () {},
  "getString" : function () {},
  "getSymKey" : function () {},
  "getSyncing" : function () {},
  "getTimezoneOffset" : function () {},
  "getToken" : function () {},
  "getTransactionReceipt" : function () {},
  "getValue" : function () {},
  "goog" : function () {},
  "greaterThanOrEqualTo" : function () {},
  "GroupMembershipUpdate" : function () {},
  "GroupMembershipUpdateHandler" : function () {},
  "guid" : function () {},
  "hashMessage" : function () {},
  "hashTransaction" : function () {},
  "hashTypedData" : function () {},
  "headers" : function () {},
  "height" : function () {},
  "hexToNumber" : function () {},
  "hexToNumberString" : function () {},
  "hexToUtf8" : function () {},
  "utf8ToHex" : function () {},
  "hide" : function () {},
  "i18n" : function () {},
  "ignoreWarnings" : function () {},
  "in" : function () {},
  "index" : function () {},
  "indexOf" : function () {},
  "init" : function () {},
  "initKeystore" : function () {},
  "injectJavaScript" : function () {},
  "installApplet" : function () {},
  "installAppletAndInitCard" : function () {},
  "Int8Array" : function () {},
  "integer" : function () {},
  "interpolate" : function () {},
  "is24Hour" : function () {},
  "isAddress" : function () {},
  "isConnected" : function () {},
  "isConnectionExpensive" : function () {},
  "isDeviceRooted" : function () {},
  "isFocused" : function () {},
  "isLinux" : function () {},
  "isMacOs" : function () {},
  "isMatches" : function () {},
  "isNaN" : function () {},
  "isUnix" : function () {},
  "isWin" : function () {},
  "isZero" : function () {},
  "Item" : function () {},
  "item" : function () {},
  "JSON" : function () {},
  "jsonEvent" : function () {},
  "keccak512" : function () {},
  "Keyboard" : function () {},
  "language" : function () {},
  "layout" : function () {},
  "layoutMeasurement" : function () {},
  "leftPad" : function () {},
  "length" : function () {},
  "LibraryDirectoryPath" : function () {},
  "Linking" : function () {},
  "locale" : function () {},
  "log" : function () {},
  "login" : function () {},
  "loginWithKeycard" : function () {},
  "logout" : function () {},
  "loop" : function () {},
  "lt" : function () {},
  "mail" : function () {},
  "map" : function () {},
  "map->GroupMembershipUpdate" : function () {},
  "MapEntry" : function () {},
  "markTrustedPeer" : function () {},
  "MaskedData" : function () {},
  "Math" : function () {},
  "Message" : function () {},
  "message" : function () {},
  "MessageHandler" : function () {},
  "MessagesSeen" : function () {},
  "MessagesSeenHandler" : function () {},
  "messaging" : function () {},
  "method" : function () {},
  "metadata": function() {},
  "minus" : function () {},
  "plus" : function () {},
  "mkdir" : function () {},
  "module" : function () {},
  "moveFile" : function () {},
  "Multihash" : function () {},
  "name" : function () {},
  "response-to": function() {},
  "content_type": function() {},
  "message_type": function() {},
  "chat_id": function() {},
  "clock": function() {},
  "nativeEvent" : function () {},
  "NativeEventEmitter" : function () {},
  "NativeModules" : function () {},
  "navigate" : function () {},
  "navigation" : function () {},
  "NavigationActions" : function () {},
  "NavigationEvents" : function () {},
  "newKeyPair" : function () {},
  "newMessageFilter" : function () {},
  "newRawMessageFilter": function() {},
  "newSymKey" : function () {},
  "nfcIsEnabled" : function () {},
  "nfcIsSupported" : function () {},
  "Notification" : function () {},
  "notification" : function () {},
  "notifications" : function () {},
  "now" : function () {},
  "Number" : function () {},
  "NumberFormatSymbols" : function () {},
  "NumberFormatSymbols_af" : function () {},
  "NumberFormatSymbols_am" : function () {},
  "NumberFormatSymbols_ar" : function () {},
  "NumberFormatSymbols_ar_DZ" : function () {},
  "NumberFormatSymbols_az" : function () {},
  "NumberFormatSymbols_be" : function () {},
  "NumberFormatSymbols_bg" : function () {},
  "NumberFormatSymbols_bn" : function () {},
  "NumberFormatSymbols_br" : function () {},
  "NumberFormatSymbols_bs" : function () {},
  "NumberFormatSymbols_cs" : function () {},
  "NumberFormatSymbols_cy" : function () {},
  "NumberFormatSymbols_da" : function () {},
  "NumberFormatSymbols_de_CH" : function () {},
  "NumberFormatSymbols_en" : function () {},
  "NumberFormatSymbols_en_AU" : function () {},
  "NumberFormatSymbols_en_CA" : function () {},
  "NumberFormatSymbols_en_IN" : function () {},
  "NumberFormatSymbols_en_SG" : function () {},
  "NumberFormatSymbols_es_419" : function () {},
  "NumberFormatSymbols_fa" : function () {},
  "NumberFormatSymbols_fil" : function () {},
  "NumberFormatSymbols_he" : function () {},
  "NumberFormatSymbols_hr" : function () {},
  "NumberFormatSymbols_hu" : function () {},
  "NumberFormatSymbols_hy" : function () {},
  "NumberFormatSymbols_id" : function () {},
  "NumberFormatSymbols_is" : function () {},
  "NumberFormatSymbols_ja" : function () {},
  "NumberFormatSymbols_ka" : function () {},
  "NumberFormatSymbols_kk" : function () {},
  "NumberFormatSymbols_km" : function () {},
  "NumberFormatSymbols_ko" : function () {},
  "NumberFormatSymbols_ky" : function () {},
  "NumberFormatSymbols_ln" : function () {},
  "NumberFormatSymbols_lo" : function () {},
  "NumberFormatSymbols_mk" : function () {},
  "NumberFormatSymbols_mn" : function () {},
  "NumberFormatSymbols_mo" : function () {},
  "NumberFormatSymbols_ms" : function () {},
  "NumberFormatSymbols_my" : function () {},
  "NumberFormatSymbols_nb" : function () {},
  "NumberFormatSymbols_ne" : function () {},
  "NumberFormatSymbols_pl" : function () {},
  "NumberFormatSymbols_pt" : function () {},
  "NumberFormatSymbols_ro" : function () {},
  "NumberFormatSymbols_ru" : function () {},
  "NumberFormatSymbols_sh" : function () {},
  "NumberFormatSymbols_si" : function () {},
  "NumberFormatSymbols_sq" : function () {},
  "NumberFormatSymbols_sv" : function () {},
  "NumberFormatSymbols_sw" : function () {},
  "NumberFormatSymbols_th" : function () {},
  "NumberFormatSymbols_tr" : function () {},
  "NumberFormatSymbols_uk" : function () {},
  "NumberFormatSymbols_ur" : function () {},
  "NumberFormatSymbols_uz" : function () {},
  "NumberFormatSymbols_vi" : function () {},
  "NumberFormatSymbols_zh" : function () {},
  "NumberFormatSymbols_zh_HK" : function () {},
  "NumberFormatSymbols_zh_TW" : function () {},
  "numberToHex" : function () {},
  "ok" : function () {},
  "onMessage" : function () {},
  "onNotification" : function () {},
  "onNotificationOpened" : function () {},
  "onTokenRefresh" : function () {},
  "openAccounts" : function () {},
  "openNfcSettings" : function () {},
  "openPicker" : function () {},
  "openURL" : function () {},
  "OS" : function () {},
  "out" : function () {},
  "p" : function () {},
  "pageY" : function () {},
  "pair" : function () {},
  "PairInstallation" : function () {},
  "PairInstallationHandler" : function () {},
  "panHandlers" : function () {},
  "PanResponder" : function () {},
  "parallel" : function () {},
  "parse" : function () {},
  "parseFloat" : function () {},
  "parseInt" : function () {},
  "password" : function () {},
  "path" : function () {},
  "payload" : function () {},
  "PermissionsAndroid" : function () {},
  "PersistentPriorityMap" : function () {},
  "PersonalRequestCommand" : function () {},
  "PersonalSendCommand" : function () {},
  "Platform" : function () {},
  "pow" : function () {},
  "Priority" : function () {},
  "Category" : function () {},
  "High" : function () {},
  "Importance" : function () {},
  "prepareDirAndUpdateConfig" : function () {},
  "Promise" : function () {},
  "props" : function () {},
  "prototype" : function () {},
  "push" : function () {},
  "quad" : function () {},
  "ReactNative" : function () {},
  "readDir" : function () {},
  "readFile" : function () {},
  "recoverAccount" : function () {},
  "reduce" : function () {},
  "register" : function () {},
  "registerComponent" : function () {},
  "registerHeadlessTask" : function () {},
  "reject" : function () {},
  "reload" : function () {},
  "remove" : function () {},
  "removeAllListeners" : function () {},
  "removeEventListener" : function () {},
  "removeKey" : function () {},
  "removeKeyWithUnpair" : function () {},
  "removeListener" : function () {},
  "repeat" : function () {},
  "request" : function () {},
  "requestMessages" : function () {},
  "requestMultiple" : function () {},
  "requestPermission" : function () {},
  "require" : function () {},
  "reset" : function () {},
  "resetGenericPassword" : function () {},
  "resetInternetCredentials" : function () {},
  "resolve" : function () {},
  "respond" : function () {},
  "rightPad" : function () {},
  "round" : function () {},
  "routeName" : function () {},
  "router" : function () {},
  "routes" : function () {},
  "saveAccountAndLogin" : function () {},
  "saveAccountAndLoginWithKeycard" : function () {},
  "schemaVersion" : function () {},
  "scrollTo" : function () {},
  "scrollToEnd" : function () {},
  "scrollToIndex" : function () {},
  "scrollToLocation" : function () {},
  "section" : function () {},
  "selection" : function () {},
  "sendDirectMessage" : function () {},
  "sendLogs" : function () {},
  "sendPairingMessage" : function () {},
  "sendPublicMessage" : function () {},
  "sendToBridge" : function () {},
  "sendTransaction" : function () {},
  "sendTransactionWithSignature" : function () {},
  "separators" : function () {},
  "sequence" : function () {},
  "set" : function () {},
  "setAutoCancel" : function () {},
  "setBackgroundColor" : function () {},
  "setBarStyle" : function () {},
  "setBlankPreviewFlag" : function () {},
  "setCategory" : function () {},
  "setChannelId" : function () {},
  "setCurrentDapp" : function () {},
  "setDockBadgeLabel" : function () {},
  "setGenericPassword" : function () {},
  "setGlobalHandler" : function () {},
  "setGroup" : function () {},
  "setHidden" : function () {},
  "setInternetCredentials" : function () {},
  "setInterval" : function () {},
  "setItem" : function () {},
  "setNativeProps" : function () {},
  "setNetworkActivityIndicatorVisible" : function () {},
  "setPriority" : function () {},
  "setShowBadge" : function () {},
  "setSmallIcon" : function () {},
  "setSoftInputMode" : function () {},
  "setSound" : function () {},
  "setString" : function () {},
  "setTimeout" : function () {},
  "setTranslucent" : function () {},
  "setUsername" : function () {},
  "setValue" : function () {},
  "sha3" : function () {},
  "Share" : function () {},
  "share" : function () {},
  "shh" : function () {},
  "show" : function () {},
  "showActionSheetWithOptions" : function () {},
  "showPicker" : function () {},
  "sign" : function () {},
  "signGroupMembership" : function () {},
  "signMessage" : function () {},
  "signTypedData" : function () {},
  "slice" : function () {},
  "SplashScreen" : function () {},
  "spring" : function () {},
  "stack" : function () {},
  "StackActions" : function () {},
  "start" : function () {},
  "startNode" : function () {},
  "state" : function () {},
  "Status" : function () {},
  "status" : function () {},
  "statusText" : function () {},
  "stop" : function () {},
  "stopAnimation" : function () {},
  "stopNode" : function () {},
  "stopWatching" : function () {},
  "stream" : function () {},
  "String" : function () {},
  "stringify" : function () {},
  "subscribe" : function () {},
  "substr" : function () {},
  "symbol" : function () {},
  "SyncInstallation" : function () {},
  "SyncInstallationHandler" : function () {},
  "t" : function () {},
  "takePictureAsync" : function () {},
  "Text" : function () {},
  "text" : function () {},
  "parsedText": function() {},
  "parsedMessage": function() {},
  "content": function() {},
  "TextEncoder" : function () {},
  "then" : function () {},
  "times" : function () {},
  "timestamp" : function () {},
  "timing" : function () {},
  "title" : function () {},
  "toAscii" : function () {},
  "toChecksumAddress" : function () {},
  "toFixed" : function () {},
  "toHex" : function () {},
  "toLocaleString" : function () {},
  "toNumber" : function () {},
  "torchMode" : function () {},
  "toString" : function () {},
  "totalSupply" : function () {},
  "toTwosComplement" : function () {},
  "toUtf8" : function () {},
  "toWei" : function () {},
  "translations" : function () {},
  "type": function() {},
  "Uint8Array" : function () {},
  "unblockPin" : function () {},
  "unlink" : function () {},
  "unpair" : function () {},
  "unpairAndDelete" : function () {},
  "updateMailservers" : function () {},
  "Uri" : function () {},
  "url" : function () {},
  "Value" : function () {},
  "ValueXY": function() {},
  "value" : function () {},
  "verify" : function () {},
  "verifyPin" : function () {},
  "Version" : function () {},
  "version" : function () {},
  "vibrate" : function () {},
  "View" : function () {},
  "viewableItems": function() {},
  "FlatList" : function () {},
  "warn" : function () {},
  "WebView" : function () {},
  "WebViewBridgeModule" : function () {},
  "width" : function () {},
  "window" : function () {},
  "writeCopyTo" : function () {},
  "x" : function () {},
  "y" : function () {},
  "YellowBox" : function () {},
  "UtcDateTime": function () {},
  "fromTimestamp": function () {},
  "ERAS": function () {},
  "ERANAMES": function () {},
  "NARROWMONTHS": function () {},
  "STANDALONENARROWMONTHS": function () {},
  "MONTHS": function () {},
  "STANDALONEMONTHS": function () {},
  "SHORTMONTHS": function () {},
  "STANDALONESHORTMONTHS": function () {},
  "WEEKDAYS": function () {},
  "STANDALONEWEEKDAYS": function () {},
  "SHORTWEEKDAYS": function () {},
  "STANDALONESHORTWEEKDAYS": function () {},
  "NARROWWEEKDAYS": function () {},
  "STANDALONENARROWWEEKDAYS": function () {},
  "SHORTQUARTERS": function () {},
  "QUARTERS": function () {},
  "AMPMS": function () {},
  "DATEFORMATS": function () {},
  "TIMEFORMATS": function () {},
  "DATETIMEFORMATS": function () {},
  "FIRSTDAYOFWEEK": function () {},
  "WEEKENDRANGE": function () {},
  "FIRSTWEEKCUTOFFDAY": function () {},
  "decimalPlaces": function () {},
  "_android": function () {},
  "next": function() {},
  "prev": function() {},
  "hasNext": function() {},
  "hasPrev": function() {},
  "rtl": function() {},
  "lineCount": function() {},
  "key": function() {},
  "keys": function() {},
  "values": function() {},
  "find": function() {},
  "insert": function() {},
  "update": function() {},
  "isSupported" : function () {},
  "authenticate" : function () {},
  "createAppContainer" : function () {},
  "useScreens" : function () {},
  "multiAccountGenerateAndDeriveAddresses" : function () {},
  "multiAccountStoreDerived" : function () {},
  "multiAccountDeriveAddresses" : function () {},
  "multiAccountReset" : function () {},
  "multiAccountLoadAccount" : function () {},
  "multiAccountStoreAccount" : function () {},
  "multiAccountImportMnemonic" : function () {},
  "multiAccountImportPrivateKey" : function () {},
  "validateMnemonic" : function () {}
}
