(ns quo.foundations.resources)

(def ui
  {:keycard-logo       (js/require "../resources/images/ui2/keycard-logo.png")
   :keycard-chip-light (js/require "../resources/images/ui2/keycard-chip-light.png")
   :keycard-chip-dark  (js/require "../resources/images/ui2/keycard-chip-dark.png")
   :keycard-watermark  (js/require "../resources/images/ui2/keycard-watermark.png")
   :bored-ape          (js/require "../resources/images/mock2/bored-ape.png")})

(def ui-themed
  {:no-funds
   {:light (js/require "../resources/images/ui2/no-funds-light.png")
    :dark  (js/require "../resources/images/ui2/no-funds-dark.png")}})

(defn get-themed-image
  [k theme]
  (get-in ui-themed [k theme]))

(defn get-image
  [k]
  (get ui k))

(def dapps
  {:coingecko (js/require "../resources/images/dapps/CoinGecko.png")
   :1inch     (js/require "../resources/images/dapps/1inch.png")
   :aave      (js/require "../resources/images/dapps/Aave.png")
   :uniswap   (js/require "../resources/images/dapps/Uniswap.png")
   :zapper    (js/require "../resources/images/dapps/Zapper.png")
   :zerion    (js/require "../resources/images/dapps/Zerion.png")})

(defn get-dapp
  [k]
  (get dapps k))

(def tokens
  {:0-native  (js/require "../resources/images/tokens/mainnet/0-native.png")
   :0xbtc     (js/require "../resources/images/tokens/mainnet/0XBTC.png")
   :1st       (js/require "../resources/images/tokens/mainnet/1ST.png")
   :abt       (js/require "../resources/images/tokens/mainnet/ABT.png")
   :abyss     (js/require "../resources/images/tokens/mainnet/ABYSS.png")
   :ae        (js/require "../resources/images/tokens/mainnet/AE.png")
   :agld      (js/require "../resources/images/tokens/mainnet/AGLD.png")
   :akro      (js/require "../resources/images/tokens/mainnet/AKRO.png")
   :amb       (js/require "../resources/images/tokens/mainnet/AMB.png")
   :ampl      (js/require "../resources/images/tokens/mainnet/AMPL.png")
   :ant       (js/require "../resources/images/tokens/mainnet/ANT.png")
   :appc      (js/require "../resources/images/tokens/mainnet/APPC.png")
   :ast       (js/require "../resources/images/tokens/mainnet/AST.png")
   :atmchain  (js/require "../resources/images/tokens/mainnet/ATMChain.png")
   :ausdc     (js/require "../resources/images/tokens/mainnet/aUSDC.png")
   :bal       (js/require "../resources/images/tokens/mainnet/BAL.png")
   :bam       (js/require "../resources/images/tokens/mainnet/BAM.png")
   :band      (js/require "../resources/images/tokens/mainnet/BAND.png")
   :bat       (js/require "../resources/images/tokens/mainnet/BAT.png")
   :blt       (js/require "../resources/images/tokens/mainnet/BLT.png")
   :blz       (js/require "../resources/images/tokens/mainnet/BLZ.png")
   :bnb       (js/require "../resources/images/tokens/mainnet/BNB.png")
   :bnt       (js/require "../resources/images/tokens/mainnet/BNT.png")
   :brln      (js/require "../resources/images/tokens/mainnet/BRLN.png")
   :btm       (js/require "../resources/images/tokens/mainnet/BTM.png")
   :btu       (js/require "../resources/images/tokens/mainnet/BTU.png")
   :cdai      (js/require "../resources/images/tokens/mainnet/cDAI.png")
   :cdt       (js/require "../resources/images/tokens/mainnet/CDT.png")
   :centra    (js/require "../resources/images/tokens/mainnet/Centra.png")
   :cfi       (js/require "../resources/images/tokens/mainnet/CFI.png")
   :ck        (js/require "../resources/images/tokens/mainnet/CK.png")
   :cnd       (js/require "../resources/images/tokens/mainnet/CND.png")
   :cob       (js/require "../resources/images/tokens/mainnet/COB.png")
   :comp      (js/require "../resources/images/tokens/mainnet/COMP.png")
   :crv       (js/require "../resources/images/tokens/mainnet/CRV.png")
   :cvc       (js/require "../resources/images/tokens/mainnet/CVC.png")
   :dai       (js/require "../resources/images/tokens/mainnet/DAI.png")
   :dat       (js/require "../resources/images/tokens/mainnet/DAT.png")
   :data      (js/require "../resources/images/tokens/mainnet/DATA.png")
   :dcn       (js/require "../resources/images/tokens/mainnet/DCN.png")
   :dgd       (js/require "../resources/images/tokens/mainnet/DGD.png")
   :dgx       (js/require "../resources/images/tokens/mainnet/DGX.png")
   :dlt       (js/require "../resources/images/tokens/mainnet/DLT.png")
   :dnt       (js/require "../resources/images/tokens/mainnet/DNT.png")
   :dpy       (js/require "../resources/images/tokens/mainnet/DPY.png")
   :drt       (js/require "../resources/images/tokens/mainnet/DRT.png")
   :dta       (js/require "../resources/images/tokens/mainnet/DTA.png")
   :edg       (js/require "../resources/images/tokens/mainnet/EDG.png")
   :edo       (js/require "../resources/images/tokens/mainnet/EDO.png")
   :ekg       (js/require "../resources/images/tokens/mainnet/EKG.png")
   :eko       (js/require "../resources/images/tokens/mainnet/EKO.png")
   :elf       (js/require "../resources/images/tokens/mainnet/ELF.png")
   :emona     (js/require "../resources/images/tokens/mainnet/EMONA.png")
   :eng       (js/require "../resources/images/tokens/mainnet/ENG.png")
   :enj       (js/require "../resources/images/tokens/mainnet/ENJ.png")
   :ens       (js/require "../resources/images/tokens/mainnet/ENS.png")
   :eos       (js/require "../resources/images/tokens/mainnet/EOS.png")
   :equad     (js/require "../resources/images/tokens/mainnet/EQUAD.png")
   :eth       (js/require "../resources/images/tokens/mainnet/ETH-token.png")
   :eth2x-fli (js/require "../resources/images/tokens/mainnet/ETH2x-FLI.png")
   :ethos     (js/require "../resources/images/tokens/mainnet/ETHOS.png")
   :evx       (js/require "../resources/images/tokens/mainnet/EVX.png")
   :fuel      (js/require "../resources/images/tokens/mainnet/FUEL.png")
   :fun       (js/require "../resources/images/tokens/mainnet/FUN.png")
   :fxc       (js/require "../resources/images/tokens/mainnet/FXC.png")
   :gdc       (js/require "../resources/images/tokens/mainnet/GDC.png")
   :gen       (js/require "../resources/images/tokens/mainnet/GEN.png")
   :glm       (js/require "../resources/images/tokens/mainnet/GLM.png")
   :gno       (js/require "../resources/images/tokens/mainnet/GNO.png")
   :gnt       (js/require "../resources/images/tokens/mainnet/GNT.png")
   :grid      (js/require "../resources/images/tokens/mainnet/GRID.png")
   :grt       (js/require "../resources/images/tokens/mainnet/GRT.png")
   :hez       (js/require "../resources/images/tokens/mainnet/HEZ.png")
   :hst       (js/require "../resources/images/tokens/mainnet/HST.png")
   :ht        (js/require "../resources/images/tokens/mainnet/HT.png")
   :icn       (js/require "../resources/images/tokens/mainnet/ICN.png")
   :icos      (js/require "../resources/images/tokens/mainnet/ICOS.png")
   :iost      (js/require "../resources/images/tokens/mainnet/IOST.png")
   :kdo       (js/require "../resources/images/tokens/mainnet/KDO.png")
   :kin       (js/require "../resources/images/tokens/mainnet/KIN.png")
   :knc       (js/require "../resources/images/tokens/mainnet/KNC.png")
   :kudos     (js/require "../resources/images/tokens/mainnet/Kudos.png")
   :lend      (js/require "../resources/images/tokens/mainnet/LEND.png")
   :link      (js/require "../resources/images/tokens/mainnet/LINK.png")
   :lisk      (js/require "../resources/images/tokens/mainnet/LISK.png")
   :loom      (js/require "../resources/images/tokens/mainnet/LOOM.png")
   :lpt       (js/require "../resources/images/tokens/mainnet/LPT.png")
   :lrc       (js/require "../resources/images/tokens/mainnet/LRC.png")
   :mana      (js/require "../resources/images/tokens/mainnet/MANA.png")
   :mco       (js/require "../resources/images/tokens/mainnet/MCO.png")
   :mda       (js/require "../resources/images/tokens/mainnet/MDA.png")
   :met       (js/require "../resources/images/tokens/mainnet/MET.png")
   :mfg       (js/require "../resources/images/tokens/mainnet/MFG.png")
   :mgo       (js/require "../resources/images/tokens/mainnet/MGO.png")
   :mkr       (js/require "../resources/images/tokens/mainnet/MKR.png")
   :mln       (js/require "../resources/images/tokens/mainnet/MLN.png")
   :moc       (js/require "../resources/images/tokens/mainnet/MOC.png")
   :mod       (js/require "../resources/images/tokens/mainnet/MOD.png")
   :mth       (js/require "../resources/images/tokens/mainnet/MTH.png")
   :mtl       (js/require "../resources/images/tokens/mainnet/MTL.png")
   :myb       (js/require "../resources/images/tokens/mainnet/MYB.png")
   :nexo      (js/require "../resources/images/tokens/mainnet/NEXO.png")
   :nexxo     (js/require "../resources/images/tokens/mainnet/NEXXO.png")
   :nmr       (js/require "../resources/images/tokens/mainnet/NMR.png")
   :npxs      (js/require "../resources/images/tokens/mainnet/NPXS.png")
   :ogn       (js/require "../resources/images/tokens/mainnet/OGN.png")
   :omg       (js/require "../resources/images/tokens/mainnet/OMG.png")
   :otn       (js/require "../resources/images/tokens/mainnet/OTN.png")
   :oxt       (js/require "../resources/images/tokens/mainnet/OXT.png")
   :pax       (js/require "../resources/images/tokens/mainnet/PAX.png")
   :paxg      (js/require "../resources/images/tokens/mainnet/PAXG.png")
   :pay       (js/require "../resources/images/tokens/mainnet/PAY.png")
   :pbtc      (js/require "../resources/images/tokens/mainnet/PBTC.png")
   :plr       (js/require "../resources/images/tokens/mainnet/PLR.png")
   :poe       (js/require "../resources/images/tokens/mainnet/POE.png")
   :poly      (js/require "../resources/images/tokens/mainnet/POLY.png")
   :powr      (js/require "../resources/images/tokens/mainnet/POWR.png")
   :ppp       (js/require "../resources/images/tokens/mainnet/PPP.png")
   :ppt       (js/require "../resources/images/tokens/mainnet/PPT.png")
   :pt        (js/require "../resources/images/tokens/mainnet/PT.png")
   :qkc       (js/require "../resources/images/tokens/mainnet/QKC.png")
   :qrl       (js/require "../resources/images/tokens/mainnet/QRL.png")
   :qsp       (js/require "../resources/images/tokens/mainnet/QSP.png")
   :r         (js/require "../resources/images/tokens/mainnet/R.png")
   :rae       (js/require "../resources/images/tokens/mainnet/RAE.png")
   :rare      (js/require "../resources/images/tokens/mainnet/RARE.png")
   :rcn       (js/require "../resources/images/tokens/mainnet/RCN.png")
   :rdn       (js/require "../resources/images/tokens/mainnet/RDN.png")
   :ren       (js/require "../resources/images/tokens/mainnet/REN.png")
   :rep       (js/require "../resources/images/tokens/mainnet/REP.png")
   :req       (js/require "../resources/images/tokens/mainnet/REQ.png")
   :rhoc      (js/require "../resources/images/tokens/mainnet/RHOC.png")
   :rlc       (js/require "../resources/images/tokens/mainnet/RLC.png")
   :rol       (js/require "../resources/images/tokens/mainnet/ROL.png")
   :sai       (js/require "../resources/images/tokens/mainnet/SAI.png")
   :salt      (js/require "../resources/images/tokens/mainnet/SALT.png")
   :san       (js/require "../resources/images/tokens/mainnet/SAN.png")
   :sngls     (js/require "../resources/images/tokens/mainnet/SNGLS.png")
   :snm       (js/require "../resources/images/tokens/mainnet/SNM.png")
   :snt       (js/require "../resources/images/tokens/mainnet/SNT.png")
   :snx       (js/require "../resources/images/tokens/mainnet/SNX.png")
   :socks     (js/require "../resources/images/tokens/mainnet/SOCKS.png")
   :spank     (js/require "../resources/images/tokens/mainnet/SPANK.png")
   :spike     (js/require "../resources/images/tokens/mainnet/SPIKE.png")
   :spn       (js/require "../resources/images/tokens/mainnet/SPN.png")
   :st        (js/require "../resources/images/tokens/mainnet/ST.png")
   :storj     (js/require "../resources/images/tokens/mainnet/STORJ.png")
   :storm     (js/require "../resources/images/tokens/mainnet/STORM.png")
   :strk      (js/require "../resources/images/tokens/mainnet/STRK.png")
   :stx       (js/require "../resources/images/tokens/mainnet/STX.png")
   :sub       (js/require "../resources/images/tokens/mainnet/SUB.png")
   :supr      (js/require "../resources/images/tokens/mainnet/SUPR.png")
   :susd      (js/require "../resources/images/tokens/mainnet/sUSD.png")
   :taas      (js/require "../resources/images/tokens/mainnet/TAAS.png")
   :taud      (js/require "../resources/images/tokens/mainnet/TAUD.png")
   :tcad      (js/require "../resources/images/tokens/mainnet/TCAD.png")
   :tgbp      (js/require "../resources/images/tokens/mainnet/TGBP.png")
   :tkn       (js/require "../resources/images/tokens/mainnet/TKN.png")
   :tkx       (js/require "../resources/images/tokens/mainnet/TKX.png")
   :tnt       (js/require "../resources/images/tokens/mainnet/TNT.png")
   :trst      (js/require "../resources/images/tokens/mainnet/TRST.png")
   :trx       (js/require "../resources/images/tokens/mainnet/TRX.png")
   :tusd      (js/require "../resources/images/tokens/mainnet/TUSD.png")
   :ubi       (js/require "../resources/images/tokens/mainnet/UBI.png")
   :ubt       (js/require "../resources/images/tokens/mainnet/UBT.png")
   :ukg       (js/require "../resources/images/tokens/mainnet/UKG.png")
   :uni       (js/require "../resources/images/tokens/mainnet/UNI.png")
   :upp       (js/require "../resources/images/tokens/mainnet/UPP.png")
   :usdc      (js/require "../resources/images/tokens/mainnet/USDC.png")
   :usds      (js/require "../resources/images/tokens/mainnet/USDS.png")
   :usdt      (js/require "../resources/images/tokens/mainnet/USDT.png")
   :veri      (js/require "../resources/images/tokens/mainnet/VERI.png")
   :vgx       (js/require "../resources/images/tokens/mainnet/VGX.png")
   :vib       (js/require "../resources/images/tokens/mainnet/VIB.png")
   :wabi      (js/require "../resources/images/tokens/mainnet/WaBi.png")
   :wbtc      (js/require "../resources/images/tokens/mainnet/WBTC.png")
   :weth      (js/require "../resources/images/tokens/mainnet/WETH.png")
   :wings     (js/require "../resources/images/tokens/mainnet/WINGS.png")
   :wtc       (js/require "../resources/images/tokens/mainnet/WTC.png")
   :xaur      (js/require "../resources/images/tokens/mainnet/XAUR.png")
   :xpa       (js/require "../resources/images/tokens/mainnet/XPA.png")
   :xrl       (js/require "../resources/images/tokens/mainnet/XRL.png")
   :xuc       (js/require "../resources/images/tokens/mainnet/XUC.png")
   :zrx       (js/require "../resources/images/tokens/mainnet/ZRX.png")
   :zsc       (js/require "../resources/images/tokens/mainnet/ZSC.png")})

(defn get-token
  [k]
  (get tokens k))

(def ^:private networks
  {:arbitrum (js/require "../resources/images/networks/Arbitrum.png")
   :ethereum (js/require "../resources/images/networks/Ethereum.png")
   :gnosis   (js/require "../resources/images/networks/Gnosis.png")
   :hermez   (js/require "../resources/images/networks/Hermez.png")
   :optimism (js/require "../resources/images/networks/Optimism.png")
   :polygon  (js/require "../resources/images/networks/Polygon.png")
   :scroll   (js/require "../resources/images/networks/Scroll.png")
   :taiko    (js/require "../resources/images/networks/Taiko.png")
   :unknown  (js/require "../resources/images/networks/Unknown.png")
   :xdai     (js/require "../resources/images/networks/xDAI.png")
   :zksync   (js/require "../resources/images/networks/zkSync.png")})

(defn get-network
  [k]
  (get networks k))
