node ('linux1'){
  stage('Git & Setup') {
  checkout([$class: 'GitSCM', branches: [[name: '$branch']],
  doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'CleanBeforeCheckout']],
  submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/status-im/status-react.git']]])
 }
  stage('Tests & Report'){
  try {withCredentials([string(credentialsId: 'TESTRAIL_PASS', variable: 'TESTRAIL_PASS'),
                        string(credentialsId: 'TESTRAIL_USER', variable: 'TESTRAIL_USER')])
          {
            sh "cd test/desktop_sikuli && python3 main.py " +
                    "--test_results_path=/${env.WORKSPACE}/test/desktop_sikuli/report " +
                    "--linux_app_url=${linux_app_url} " +
                    "--testrail_report=True " +
                    "--jenkins_build_num=${env.BUILD_NUMBER}"}}
  finally {
            archiveArtifacts 'test/desktop_sikuli/report/*.png'}
  }
}
