(ns status-im.react-native.js-dependencies)

(def config                 (js/require "react-native-config"))
(def fs                     (js/require "react-native-fs"))
(def http-bridge            (js/require "react-native-http-bridge"))
(def keychain               (js/require "react-native-keychain"))
(def qr-code                (js/require "react-native-qrcode"))
(def react-native           (js/require "react-native"))
(def realm                  (js/require "realm"))
(def webview-bridge         (js/require "react-native-webview-bridge"))
(def webview                #js {:WebView #js {}})
(def secure-random          (.-generateSecureRandom (js/require "react-native-securerandom")))
(def EventEmmiter           (js/require "react-native/Libraries/vendor/emitter/EventEmitter"))
(def fetch                  (.-default (js/require "react-native-fetch-polyfill")))
(def i18n                   (js/require "i18n-js"))
(def react-native-languages (.-default (js/require "react-native-languages")))
(def desktop-linking        (.-DesktopLinking (.-NativeModules react-native)))
(def desktop-menu           (js/require "react-native-desktop-menu"))
(def desktop-config         (js/require "react-native-desktop-config"))
(def desktop-shortcuts      (js/require "react-native-desktop-shortcuts"))
(def react-native-firebase  #js {})
(def camera                 #js {:default #js {:constants {:Aspect "Portrait"}}})
(def status-keycard         #js {:default #js {}})
(def dialogs                #js {})
(def dismiss-keyboard       #js {})
(def image-crop-picker      #js {})
(def image-resizer          #js {})
(def nfc                    #js {})
(def svg                    #js {})
(def snoopy                 #js {})
(def snoopy-filter          #js {})
(def snoopy-bars            #js {})
(def snoopy-buffer          #js {})
(def background-timer       #js {:setTimeout (fn [cb ms] (js/setTimeout cb ms))})
(def react-navigation       (js/require "react-navigation"))
(def react-native-shake     #js {})
(def react-native-mail      #js {:mail (fn [])})
