(ns status-im.react-native.js-dependencies)

(def camera                 #js {:constants {:Aspect "Portrait"}})
(def config                 (js/require "react-native-config"))
(def dialogs                #js {})
(def dismiss-keyboard       #js {})
(def fs                     (js/require "react-native-fs"))
(def http-bridge            (js/require "react-native-http-bridge"))
;; i18n is now exported in default object of the module
;; https://github.com/AlexanderZaytsev/react-native-i18n/blob/master/index.js
(def i18n                   (js/require "react-native-i18n"))
(def image-crop-picker      #js {})
(def image-resizer          #js {})
(def instabug               #js {:IBGLog ( fn [])})
(def keychain               (js/require "react-native-keychain"))
(def nfc                    #js {})
(def qr-code                (js/require "react-native-qrcode"))
(def react-native           (js/require "react-native"))
(def realm                  (js/require "realm"))
(def webview-bridge         (js/require "react-native-webview-bridge"))
(def secure-random          (.-generateSecureRandom (js/require "react-native-securerandom")))
(def svg                    #js {})
(def react-native-fcm       #js {:default #js {:getFCMToken (fn [])
                                               :requestPermissions (fn [])}})
(def snoopy                 #js {})
(def snoopy-filter          #js {})
(def snoopy-bars            #js {})
(def snoopy-buffer          #js {})
(def EventEmmiter           (js/require "react-native/Libraries/vendor/emitter/EventEmitter"))
(def background-timer       #js {:setTimeout (fn [])})
(def fetch                  (.-default (js/require "react-native-fetch-polyfill")))
(def testfairy #js {})

