(ns status-im.react-native.resources)

(def contacts
  {:auction-house      (js/require "./resources/images/contacts/auction-house.png")
   :mkr-market         (js/require "./resources/images/contacts/mkr-market.png")
   :oaken-water-meter  (js/require "./resources/images/contacts/oaken-water-meter.png")
   :flight-delays-suck (js/require "./resources/images/contacts/flight-delays-suck.png")
   :jarrad             (js/require "./resources/images/contacts/jarrad.png")
   :firstblood         (js/require "./resources/images/contacts/FirstBlood.png")
   :gnosis             (js/require "./resources/images/contacts/gnosis.png")
   :melonport          (js/require "./resources/images/contacts/melonport.png")
   :bchat              (js/require "./resources/images/contacts/bchat.png")
   :dentacoin          (js/require "./resources/images/contacts/Dentacoin.png")
   :augur              (js/require "./resources/images/contacts/augur.png")
   :ethlance           (js/require "./resources/images/contacts/ethlance.png")
   :commiteth          (js/require "./resources/images/contacts/commiteth.png")
   :etherplay          (js/require "./resources/images/contacts/etherplay.png")})
