(ns status-im.ui.screens.routing.back-actions)

(def back-actions {:chat                              :default
                   :login                             :default
                   :recover-multiaccount-enter-phrase :default
                   :create-multiaccount-generate-key  :default
                   :new-chat                          :default
                   :new-public-chat                   :default
                   :wallet-account                    :default
                   :add-new-account                   :default
                   :add-new-account-password          :default
                   :about-app                         :default
                   :help-center                       :default
                   :advanced-settings                 :default
                   :sync-settings                     :default
                   :mobile-network-settings           :default
                   :offline-messaging-settings        :default
                   :edit-mailserver                   :default
                   :installations                     :default
                   :privacy-and-security              :default
                   :dapps-permissions                 :default
                   :contacts-list                     :default
                   :blocked-users-list                :default
                   :ens-main                          :default
                   :ens-register                      :default
                   :wallet-settings-assets            :default
                   :wallet-add-custom-token           :default
                   :currency-settings                 :default
                   :backup-seed                       :default})