require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!
# install! 'cocoapods', :deterministic_uuids => false

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

# ENV['RCT_NEW_ARCH_ENABLED'] = "1"

abstract_target 'Status' do
  # Pods for StatusQuo
  config = use_native_modules!

 # Flags change depending on the env values.
 flags = get_default_flags()

 use_react_native!(:path => config[:reactNativePath],
   # to enable hermes on iOS, change `false` to `true` and then install pods
     :hermes_enabled => false,
     :fabric_enabled => false,
     # An absolute path to your application root.
     :app_path => "#{Pod::Config.instance.installation_root}/.."
     )

 post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end

  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'
  pod 'react-native-config', :path => '../node_modules/react-native-config'

  pod 'SQLCipher', '~>3.0'
  pod 'SSZipArchive', '2.4.3'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"

  pod "react-native-status-keycard", path: "../node_modules/react-native-status-keycard"
  pod "react-native-status", path: "../modules/react-native-status"
  pod "Keycard", git: "https://github.com/status-im/Keycard.swift.git"
  pod 'secp256k1', git: "https://github.com/status-im/secp256k1.swift.git", submodules: true

  target 'StatusIm' do

    target 'StatusImTests' do
      inherit! :complete
      # Pods for testing
    end
  end

  target 'StatusImPR' do
  end

  use_native_modules!
end

