(ns status-im.js-dependencies)

(defn Chance []           (js/require "chance"))
(defn emojis []           (js/require "emojilib"))
(defn phishing-detect []  (js/require "eth-phishing-detect"))
(defn homoglyph-finder [] (js/require "homoglyph-finder"))
(defn identicon-js []     (js/require "identicon.js"))
(def Web3                 (js/require "web3"))
(defn web3-prototype []   (.-prototype Web3))
(defn text-encoding []    (js/require "text-encoding"))
(defn js-sha3 []          (js/require "js-sha3"))
(defn web3-utils []       (js/require "web3-utils"))
(defn hi-base32 []        (js/require "hi-base32"))
