(ns status-im.js-dependencies)

(def Chance           (js/require "chance"))
(def emojis           (js/require "emojilib"))
(def phishing-detect  (js/require "eth-phishing-detect"))
(def identicon-js     (js/require "identicon.js"))
(def Web3             (js/require "web3"))
(def web3-prototype   (.-prototype Web3))
(def web3-utils       (js/require "web3-utils"))
(def hi-base32        (js/require "hi-base32"))
