(ns status-im.js-dependencies)

(def Chance              (js/require "chance"))
(def emojis              (js/require "emojilib"))
(def phishing-detect     (js/require "eth-phishing-detect"))
(def homoglyph-finder    (js/require "homoglyph-finder"))
(def identicon-js        (js/require "identicon.js"))
(def Web3                (js/require "web3"))
(def text-encoding       (js/require "text-encoding"))
(def js-sha3             (js/require "js-sha3"))
