(ns status-im.resources)

(def add-icon (js/require "./images/add.png"))
(def att (js/require "./images/att.png"))
(def chat-icon (js/require "./images/chat.png"))
(def delivered-icon (js/require "./images/delivered.png"))
(def delivery-failed-icon (js/require "./images/deliveryfailed.png"))
(def icon-close-gray (js/require "./images/icon_close_gray.png"))
(def leave-icon (js/require "./images/leave.png"))
(def logo-icon (js/require "./images/logo.png"))
(def mic (js/require "./images/mic.png"))
(def nav-back-icon (js/require "./images/nav-back.png"))
(def user-no-photo (js/require "./images/no-photo.png"))
(def online-icon (js/require "./images/online.png"))
(def play (js/require "./images/play.png"))
(def seen-icon (js/require "./images/seen.png"))
(def smile (js/require "./images/smile.png"))
(def trash-icon (js/require "./images/trash.png"))
(def v (js/require "./images/v.png"))

(def contacts
  {:auction-house (js/require "./images/contacts/auction-house.png")
   :mkr-market (js/require "./images/contacts/mkr-market.png")
   :oaken-water-meter (js/require "./images/contacts/oaken-water-meter.png")
   :flight-delays-suck (js/require "./images/contacts/flight-delays-suck.png")
   :jarrad (js/require "./images/contacts/jarrad.png")
   :firstblood (js/require "./images/contacts/FirstBlood.png")
   :gnosis (js/require "./images/contacts/gnosis.png")})
