source 'https://rubygems.org'

gem 'fastlane', '>= 2.131.0'

plugins_path = ENV['FASTLANE_PLUGINFILE_PATH']

if plugins_path == nil
    plugins_path = File.join(__dir__, 'Pluginfile')
end

eval_gemfile(plugins_path) if plugins_path
