source 'https://rubygems.org'

gem 'fastlane', '>= 2.131.0'

plugins_path = ENV['FASTLANE_PLUGINFILE_PATH'] ||
               File.join(__dir__, 'Pluginfile')
eval_gemfile(plugins_path) if plugins_path
