source "https://rubygems.org"

gem "fastlane", ">= 2.127.2"

plugins_path = File.join(File.dirname(__FILE__), 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)

plugins_path = ENV["FASTLANE_PLUGINFILE_PATH"]
eval_gemfile(plugins_path) if plugins_path