(ns status-im.subs.market
  (:require
    [re-frame.core :as rf]))

(rf/reg-sub
 :market/tokens
 (fn [_db _]
   [{:token             :btc
     :token-rank        1
     :token-name        "Bitcoin"
     :market-cap        "$1.63T"
     :price             "$82,275.52"
     :percentage-change 4.35}
    {:token             :eth
     :token-rank        2
     :token-name        "Ethereum"
     :market-cap        "$188.13B"
     :price             "$1,558.92"
     :percentage-change 4.15}
    {:token             :usdt
     :token-rank        3
     :token-name        "Tether"
     :market-cap        "$144.24B"
     :price             "$0.9993"
     :percentage-change -0.0001}
    {:token             :xrp
     :token-rank        5
     :token-name        "Tether"
     :market-cap        "$144.24B"
     :price             "$0.9993"
     :percentage-change -0.0001}
    {:token             :bnb
     :token-rank        6
     :token-name        "Tether"
     :market-cap        "$144.24B"
     :price             "$0.9993"
     :percentage-change -0.0001}
    {:token             :sol
     :token-rank        7
     :token-name        "Tether"
     :market-cap        "$144.24B"
     :price             "$0.9993"
     :percentage-change -0.0001}
    {:token             :usdc
     :token-rank        8
     :token-name        "Tether"
     :market-cap        "$144.24B"
     :price             "$0.9993"
     :percentage-change -0.0001}
    {:token             :btc
     :token-rank        1
     :token-name        "Bitcoin"
     :market-cap        "$1.63T"
     :price             "$82,275.52"
     :percentage-change 4.35}
    {:token             :eth
     :token-rank        2
     :token-name        "Ethereum"
     :market-cap        "$188.13B"
     :price             "$1,558.92"
     :percentage-change 4.15}
    {:token             :usdt
     :token-rank        3
     :token-name        "Tether"
     :market-cap        "$144.24B"
     :price             "$0.9993"
     :percentage-change -0.0001}
    {:token             :xrp
     :token-rank        5
     :token-name        "Tether"
     :market-cap        "$144.24B"
     :price             "$0.9993"
     :percentage-change -0.0001}
    {:token             :bnb
     :token-rank        6
     :token-name        "Tether"
     :market-cap        "$144.24B"
     :price             "$0.9993"
     :percentage-change -0.0001}
    {:token             :sol
     :token-rank        7
     :token-name        "Tether"
     :market-cap        "$144.24B"
     :price             "$0.9993"
     :percentage-change -0.0001}
    {:token             :usdc
     :token-rank        8
     :token-name        "Tether"
     :market-cap        "$144.24B"
     :price             "$0.9993"
     :percentage-change -0.0001}]))
