# Auto-generated by ../tools/maven/maven-inputs2nix.sh
{ }:

let
  repositories = {
    apache = "https://repo1.maven.org/maven2";
    clojars = "https://repo.clojars.org";
    fabric-io = "https://maven.fabric.io/public";
    google = "https://dl.google.com/dl/android/maven2";
    gradle = "http://repo.gradle.org/gradle/libs-releases-local";
    gradlePlugins = "https://plugins.gradle.org/m2";
    java = "https://maven.java.net/content/repositories/releases";
    jcenter = "https://jcenter.bintray.com";
    jitpack = "https://jitpack.io";
    maven = "https://repo1.maven.org/maven2";
    sonatypeSnapshots =
      "https://oss.sonatype.org/content/repositories/snapshots";
    sonatypePublicGrid =
      "https://repository.sonatype.org/content/groups/sonatype-public-grid";
  };

in {
  "https://repo.clojars.org/binaryage/env-config/0.2.2/env-config-0.2.2" =
  {
    host = repositories.clojars;
    path =
      "binaryage/env-config/0.2.2/env-config-0.2.2";
    type = "jar";
    pom = {
      sha1 = "8a8f0d726bb150b074dbaa92da5470f6144adb76";
      sha256 = "07x1a046xcg9bbzwwgls8i036lzryv5ix29c8m0hf3pp742xa49v";
    };
    jar = {
      sha1 = "ac36173f1802a5d7225be41faebedbf12949ae59";
      sha256 = "11j1bls84d8hn8gviawvxkbbnb0hcg1lvw6qqcjj356ap6xzxfic";
    };
  };
  "https://repo.clojars.org/binaryage/oops/0.7.0/oops-0.7.0" =
  {
    host = repositories.clojars;
    path =
      "binaryage/oops/0.7.0/oops-0.7.0";
    type = "jar";
    pom = {
      sha1 = "de223223c4272ce9ee75c81f8764e894029630b4";
      sha256 = "0sz21344v8lxd6mjlrb8r8yyz934h4lnkwqlpg3csgsi11mppya3";
    };
    jar = {
      sha1 = "9729401b4c6551f6becf44cf0818d04255410099";
      sha256 = "0jkdybj37q3a4vvay3asj47ms7l3qjpidhkk30293w0zc7jk18k8";
    };
  };
  "https://repo.clojars.org/clj-stacktrace/clj-stacktrace/0.2.5/clj-stacktrace-0.2.5" =
  {
    host = repositories.clojars;
    path =
      "clj-stacktrace/clj-stacktrace/0.2.5/clj-stacktrace-0.2.5";
    type = "jar";
    pom = {
      sha1 = "c4d8726888bedd0ff415f1a90eb326edc0772d84";
      sha256 = "00wvqa548pmfhkbkf8lx7325pmgqxdm8jmk8ph76w3gwlkwalpqn";
    };
    jar = {
      sha1 = "1d811ed4a7eeee8ffe08e140eddb38429f4e6cdd";
      sha256 = "1h4wc8iw87cqp20l1wfkh7kxa1ik64ybdw5zh97wxhcsa7bchhzg";
    };
  };
  "https://repo.clojars.org/cljfmt/cljfmt/0.5.7/cljfmt-0.5.7" =
  {
    host = repositories.clojars;
    path =
      "cljfmt/cljfmt/0.5.7/cljfmt-0.5.7";
    type = "jar";
    pom = {
      sha1 = "3e368e434c19c97811ec501226ade1089c81d199";
      sha256 = "1djm9wiq96ghd2v697m8vwkxxfv9js7168y5xclmsbhgxgp43wh4";
    };
    jar = {
      sha1 = "f6bf9e4e21c824fafe19a67e3001e38c6d98c18f";
      sha256 = "0302s3kyc2p1rbrq58dqhjinq46i6rcivn7afk0lkd213dpnxr1b";
    };
  };
  "https://repo.clojars.org/cljs-bean/cljs-bean/1.3.0/cljs-bean-1.3.0" =
  {
    host = repositories.clojars;
    path =
      "cljs-bean/cljs-bean/1.3.0/cljs-bean-1.3.0";
    type = "jar";
    pom = {
      sha1 = "2920ec4ae47eaa47c8a8aeecb4670a42cd412aab";
      sha256 = "0xamxny72ymyjfnmzjbnxfc0b19rbbzsmxgm6x2d5z2fbsgv3hz7";
    };
    jar = {
      sha1 = "eef0aae8057df9c538bf009fd82766d5e86848c7";
      sha256 = "0c6wlpyc1k5aavw5dixllycdnmr64rrhpc4q57wfyfymixz87d7w";
    };
  };
  "https://repo.clojars.org/cljsbuild/cljsbuild/1.1.7/cljsbuild-1.1.7" =
  {
    host = repositories.clojars;
    path =
      "cljsbuild/cljsbuild/1.1.7/cljsbuild-1.1.7";
    type = "jar";
    pom = {
      sha1 = "16ffd768ec441b967b533aac54c221bd49636bee";
      sha256 = "0bsnlcwv1mg5rc1ga7df3arjkhl23p39vjxjn06lvka7z0gj8azn";
    };
    jar = {
      sha1 = "b83ee61540c18c694dee53edd8b53354e560c260";
      sha256 = "0xj9k8n3b31aavlf3fdrbqjflkdmqlvl34fz7s1iv8ff0kvb3aa6";
    };
  };
  "https://repo.clojars.org/cljsjs/react-dom-server/16.13.0-0/react-dom-server-16.13.0-0" =
  {
    host = repositories.clojars;
    path =
      "cljsjs/react-dom-server/16.13.0-0/react-dom-server-16.13.0-0";
    type = "jar";
    pom = {
      sha1 = "320f6487531caf52b15ef10d43129b80c40f7c35";
      sha256 = "1l9s4akd1s06xcx0r38h6xf82bcr0ypmaw6xnvdrmll19a3g9ilc";
    };
    jar = {
      sha1 = "4d400ae4f66687286170eb691aa8e642fe87aa47";
      sha256 = "0fzwd6hfb2rx85pr6fsr2r4x76a90wgnjgnv23jzfn1vw6znch07";
    };
  };
  "https://repo.clojars.org/cljsjs/react-dom/16.13.0-0/react-dom-16.13.0-0" =
  {
    host = repositories.clojars;
    path =
      "cljsjs/react-dom/16.13.0-0/react-dom-16.13.0-0";
    type = "jar";
    pom = {
      sha1 = "367f3754430e092e8c9a5a9f58955fa68389401b";
      sha256 = "0x5klcq3bdbckfi6dqy160rd2r9g3593gp86ha7a6b7p2sfrvmal";
    };
    jar = {
      sha1 = "b87b10a7d48e1c773eedfeb737f680a5566b7321";
      sha256 = "10d9l42v7g78gpv6xklydywlpbvpxiky6gw1w3hnzrlqgbd40ip1";
    };
  };
  "https://repo.clojars.org/cljsjs/react/16.13.0-0/react-16.13.0-0" =
  {
    host = repositories.clojars;
    path =
      "cljsjs/react/16.13.0-0/react-16.13.0-0";
    type = "jar";
    pom = {
      sha1 = "66011033045a6aaa778c01ed308675fa008817f0";
      sha256 = "1j17bw4vmi26782v84znxnrx1qpi0wm6agbpczds0gb5f9nr2myv";
    };
    jar = {
      sha1 = "b72f3f9a69ec4039ac57597859ea4b5d1cfcd113";
      sha256 = "1dp4pi9jphncifa56kqj6sri8vwl62ia1xy3ii70fba1mdjij63s";
    };
  };
  "https://repo.clojars.org/com/andrewmcveigh/cljs-time/0.5.2/cljs-time-0.5.2" =
  {
    host = repositories.clojars;
    path =
      "com/andrewmcveigh/cljs-time/0.5.2/cljs-time-0.5.2";
    type = "jar";
    pom = {
      sha1 = "21a75819b0540486c66a48bd9119201c368221ba";
      sha256 = "035awyqyifbgn28faz0q90hm66vngdcl9x6jgbmkh5zjnp1xmpfi";
    };
    jar = {
      sha1 = "7d4274be169f54a03d4afcc40ea95f40d44ca0a2";
      sha256 = "061cjh2a6qpkib5v5mdrsbwhvcbqvh1igvp3b7jhcfj05pgplm1x";
    };
  };
  "https://repo.clojars.org/com/taoensso/encore/2.91.0/encore-2.91.0" =
  {
    host = repositories.clojars;
    path =
      "com/taoensso/encore/2.91.0/encore-2.91.0";
    type = "jar";
    pom = {
      sha1 = "17b8d661cb1d3f14434af9934e1b5bf35dedf922";
      sha256 = "17g1sihagxmv33f8fs40dhw5ni3d25iwj7ipivfj4yzldqaifxz6";
    };
    jar = {
      sha1 = "b3763f399395938eb66f0b125f8d9559976bf168";
      sha256 = "1a051xqn2k4gjnb9lvs6ma3qwdx14vqnq32z7qpqda6h3cyymvq5";
    };
  };
  "https://repo.clojars.org/com/taoensso/encore/2.94.0/encore-2.94.0" =
  {
    host = repositories.clojars;
    path =
      "com/taoensso/encore/2.94.0/encore-2.94.0";
    type = "jar";
    pom = {
      sha1 = "73fed0c1c6bb76edf667bda84322dd41e478615c";
      sha256 = "1d87b3g6lpr6nnvyhlsx3zw6wm1ccmh3lqzi13q4y34cp0grcmdf";
    };
    jar = {
      sha1 = "753c6e5510eaa9794d0bb092dd7c1f2f862a80e8";
      sha256 = "172f96w54311ckj6grs9kz0ddxgdqgdngqmzjg77qw5r3rsixyyh";
    };
  };
  "https://repo.clojars.org/com/taoensso/truss/1.5.0/truss-1.5.0" =
  {
    host = repositories.clojars;
    path =
      "com/taoensso/truss/1.5.0/truss-1.5.0";
    type = "jar";
    pom = {
      sha1 = "dd64379ae860c87098eea582d30a48e887f9748e";
      sha256 = "01j47fp91zv5g8yd5ayhnfgm59zsiq5wcicyjjpnkhy9nsw5vl5h";
    };
    jar = {
      sha1 = "ef3f595da76cbcbe40124ee0a858b7ca635d30f2";
      sha256 = "1a49slgn2py6mxghwmq70nm9k4s27kmvp3cgnv6v2fi5zvkphwrs";
    };
  };
  "https://repo.clojars.org/fs/fs/1.1.2/fs-1.1.2" =
  {
    host = repositories.clojars;
    path =
      "fs/fs/1.1.2/fs-1.1.2";
    type = "jar";
    pom = {
      sha1 = "5eca710d59b516b82f4add0f30b1751efffdb1e9";
      sha256 = "06c7qdmy4qknmiqfmjk8i1sl2sri061k36bqa026flrha3hzpqx5";
    };
    jar = {
      sha1 = "bfbda6c3d0c91ae5a368a9465464a47840df44ef";
      sha256 = "1bd1yhmz16ja09r0j3g33dq5xzc9gsa0cbi2m5whv0bk1jafz36k";
    };
  };
  "https://repo.clojars.org/hickory/hickory/0.7.1/hickory-0.7.1" =
  {
    host = repositories.clojars;
    path =
      "hickory/hickory/0.7.1/hickory-0.7.1";
    type = "jar";
    pom = {
      sha1 = "5730f6d94df251fc3082ee7d0610a1a6b5327859";
      sha256 = "0yhfpg8ivqyxg8615bvg3a0ljw0mxgqd2nis5gwhf9xn6p1id6x5";
    };
    jar = {
      sha1 = "d9e6114592c434ca1df6022bbf4d5e97714666ee";
      sha256 = "021ag1b00821ma6mfl66ljyza1avjlpcld0zhnz1gvppwm5974xz";
    };
  };
  "https://repo.clojars.org/io/aviso/pretty/0.1.33/pretty-0.1.33" =
  {
    host = repositories.clojars;
    path =
      "io/aviso/pretty/0.1.33/pretty-0.1.33";
    type = "jar";
    pom = {
      sha1 = "bd20d3111649da92524569882f0f9925740aac3e";
      sha256 = "034rhbp6cqzbf9c4ql28n72vmqbxvh39ghf1b2axlnfza38w783b";
    };
    jar = {
      sha1 = "2ebf75b7ff2a2260827453e7ea98e012a9eca3e2";
      sha256 = "06w7hpgccr7qy47cwzpq5h2fw27am1imc9cbpg3bc5bbydz9q4df";
    };
  };
  "https://repo.clojars.org/lein-cljfmt/lein-cljfmt/0.5.7/lein-cljfmt-0.5.7" =
  {
    host = repositories.clojars;
    path =
      "lein-cljfmt/lein-cljfmt/0.5.7/lein-cljfmt-0.5.7";
    type = "jar";
    pom = {
      sha1 = "1130335a2e2dba720bb0779c4f05097bb0341b1f";
      sha256 = "14ra5xi3nsa1lkid3h1nnih9ihkz0772f82i70x4jljr40wn0cx1";
    };
    jar = {
      sha1 = "9389a15fec0914dfcf48c08a69f44dd71133e62c";
      sha256 = "18xgma82lpmiqzs66jm41i1jq7sjv5ma6lnz6ksxyv08r75xhf8q";
    };
  };
  "https://repo.clojars.org/lein-cljsbuild/lein-cljsbuild/1.1.7/lein-cljsbuild-1.1.7" =
  {
    host = repositories.clojars;
    path =
      "lein-cljsbuild/lein-cljsbuild/1.1.7/lein-cljsbuild-1.1.7";
    type = "jar";
    pom = {
      sha1 = "ef82f47435ac6af478571640ccf45f4fc019869d";
      sha256 = "00ikz9csmlw410pz8ilq0bz57icinczzlrw8hgx6zgbbqh57p297";
    };
    jar = {
      sha1 = "925e24bd16c868457d1608f6a7d96951a9c12e7f";
      sha256 = "0ihj2dd3lpz3banpqm0pgcj8sd5wywkjy7mxyjyckgb6g48ahf3l";
    };
  };
  "https://repo.clojars.org/meta-merge/meta-merge/1.0.0/meta-merge-1.0.0" =
  {
    host = repositories.clojars;
    path =
      "meta-merge/meta-merge/1.0.0/meta-merge-1.0.0";
    type = "jar";
    pom = {
      sha1 = "5d5967dd4a746e4a9fd1927fc78098dd424ea576";
      sha256 = "0carx82c5anc6i0lbi40nhzwas1dynag6c8h6k8jpk6fixjj02mh";
    };
    jar = {
      sha1 = "28cbe836fdf7de02801fe0bdbb30eb2fd842e8d9";
      sha256 = "1iq2xf10as0h1q4vqb51hq0xf211f6ijmrv28pjy01npwgiy5znp";
    };
  };
  "https://repo.clojars.org/mvxcvi/alphabase/1.0.0/alphabase-1.0.0" =
  {
    host = repositories.clojars;
    path =
      "mvxcvi/alphabase/1.0.0/alphabase-1.0.0";
    type = "jar";
    pom = {
      sha1 = "2cd07338e4e0a8f7f20d26c8212e5a3333c7acac";
      sha256 = "1kan1lb3ckc0l447cj3l83lh6svz5bk514j0y9lxif6is07b2qxg";
    };
    jar = {
      sha1 = "008785c0ff977d8132af4aaa931d88ffc44fca03";
      sha256 = "1g395and521h2q370vh7w0psx63a1zb5f2rcrafqgzw5s3nwlm4q";
    };
  };
  "https://repo.clojars.org/net/cgrand/macrovich/0.2.1/macrovich-0.2.1" =
  {
    host = repositories.clojars;
    path =
      "net/cgrand/macrovich/0.2.1/macrovich-0.2.1";
    type = "jar";
    pom = {
      sha1 = "8b596c51c4d541ce1cc936bba18ef4d0b8d4aac1";
      sha256 = "1ajpbx1bk2bp5f6zvs0yc6ikzx816l9jm2fchbn0mmlb4x4nmdxp";
    };
    jar = {
      sha1 = "abcb26cbfe0f8eef363b25525210c0fe1eb1f693";
      sha256 = "119rmznkfsk1df3q9408dkd9kcqsbpffni19dzrjr7k05ijcl487";
    };
  };
  "https://repo.clojars.org/quoin/quoin/0.1.2/quoin-0.1.2" =
  {
    host = repositories.clojars;
    path =
      "quoin/quoin/0.1.2/quoin-0.1.2";
    type = "jar";
    pom = {
      sha1 = "cdabd1b76f3a86c59260cd25be534a0a5b67c302";
      sha256 = "0wv7m5l9hafc0ysxg7g7fqmdq94dxmv13cj37il69wvagqskarhc";
    };
    jar = {
      sha1 = "0dbbb28df3e337233f934468915eb327ff488172";
      sha256 = "0b5rc1cmbgg8qpl80jyvh0ldgs7dv86c0qxixazdnz05limmnpb5";
    };
  };
  "https://repo.clojars.org/rasom/lein-githooks/0.1.5/lein-githooks-0.1.5" =
  {
    host = repositories.clojars;
    path =
      "rasom/lein-githooks/0.1.5/lein-githooks-0.1.5";
    type = "jar";
    pom = {
      sha1 = "ec0b1322dd8d9dba726dd0f95548a216094c488b";
      sha256 = "0zf7hv0hkpfjlvxbl274jm5m23avvrlj7wwpqpq019pnwssv2r5j";
    };
    jar = {
      sha1 = "727bdd86ef414cd99f2f4f68c56348db898048ab";
      sha256 = "0jg72qqzfi7qf2yzwisjpbcw4a68lq7j5nra9zgjqw1h3nanwsgi";
    };
  };
  "https://repo.clojars.org/re-frame/re-frame/0.12.0/re-frame-0.12.0" =
  {
    host = repositories.clojars;
    path =
      "re-frame/re-frame/0.12.0/re-frame-0.12.0";
    type = "jar";
    pom = {
      sha1 = "41fd34c15c1cf68eec81435e09d0a79fd8a88276";
      sha256 = "08c3sxi3sdkay3550vb3gbv5czzdh2kyin4mb8cpd2wd5g2c88sq";
    };
    jar = {
      sha1 = "3ff92169fe7588ad62dad2d6ea3bf0e5d3e2d224";
      sha256 = "1m5sjskgjx028s1zpa631bp52y9hjn8l1nr8hrwiwdh09i2kpnk2";
    };
  };
  "https://repo.clojars.org/reagent/reagent/0.10.0/reagent-0.10.0" =
  {
    host = repositories.clojars;
    path =
      "reagent/reagent/0.10.0/reagent-0.10.0";
    type = "jar";
    pom = {
      sha1 = "0ced0db04eaf77ec3dfa7a3f56cc022fe2814d8b";
      sha256 = "15cqnfwkzxia6bdjq1kism72jf66zdpldk0925313z41ynkqfr8r";
    };
    jar = {
      sha1 = "1a88fae22cd0f7f66bb181aa520da264a82f6942";
      sha256 = "0vdvm75rpcq9kx2sp0jd2lsa70fv2xymy1g55ss972s85p5j50bm";
    };
  };
  "https://repo.clojars.org/reagent/reagent/0.7.0/reagent-0.7.0" =
  {
    host = repositories.clojars;
    path =
      "reagent/reagent/0.7.0/reagent-0.7.0";
    type = "jar";
    pom = {
      sha1 = "1d9d0bee8896bb3b4dfc770c6d93c506e903712d";
      sha256 = "1arybi02a4svi926sw4yljl3fc7qsjk1b0z8r5h74j3wqwczz3ba";
    };
    jar = {
      sha1 = "5a4da4cfb9fc0e545ad64bb23fbde2c67dd1371b";
      sha256 = "19y0b1xkamrp6rj8p9is7fhz9zgzz1wpzdk59a24mxw4fiw5d1ls";
    };
  };
  "https://repo.clojars.org/rewrite-clj/rewrite-clj/0.5.2/rewrite-clj-0.5.2" =
  {
    host = repositories.clojars;
    path =
      "rewrite-clj/rewrite-clj/0.5.2/rewrite-clj-0.5.2";
    type = "jar";
    pom = {
      sha1 = "82b78a539f4cedd824dbb74585118a03045abad7";
      sha256 = "1vfva7p1m17aga50s79w76gpc3wvkhf9fiqmhka7kv08yrqzn4z6";
    };
    jar = {
      sha1 = "b41bc0697d82e686ea9b293d3f3adb2fc7be6737";
      sha256 = "1fm9bkd3wiqxalldqdfwh5n5cvlichp5an355c0lnkhi5l1hpfvl";
    };
  };
  "https://repo.clojars.org/rewrite-cljs/rewrite-cljs/0.4.3/rewrite-cljs-0.4.3" =
  {
    host = repositories.clojars;
    path =
      "rewrite-cljs/rewrite-cljs/0.4.3/rewrite-cljs-0.4.3";
    type = "jar";
    pom = {
      sha1 = "9da639eac10f66ab57057b75e59ce87200457f54";
      sha256 = "1dn85fa8j4dni7lpzvvwk3y2lp69grpp7rjy0pla7j7l35a9nqpp";
    };
    jar = {
      sha1 = "eddfed4a28f3865322e479ba77e84985421466bd";
      sha256 = "0gqsj9y66ssxm7qbgqps9548gvrmzdpd16zh6gr6jppqwxgwvawv";
    };
  };
  "https://repo.clojars.org/status-im/timbre/4.10.0-2-status/timbre-4.10.0-2-status" =
  {
    host = repositories.clojars;
    path =
      "status-im/timbre/4.10.0-2-status/timbre-4.10.0-2-status";
    type = "jar";
    pom = {
      sha1 = "a0ada642eec4fc748cc52988754ad5cdfa1865b1";
      sha256 = "1h7hhxq1kqpm2g0sk811zigi8c66si72l141gh964ly4pldpc940";
    };
    jar = {
      sha1 = "e630bd13a422d7dbedeeb26f17aca0a473a9e5d3";
      sha256 = "1ipakbl438xkj1qhp6lrmjk25vihk15v86k69qba4ny7i0jhyj21";
    };
  };
  "https://repo.clojars.org/viebel/codox-klipse-theme/0.0.1/codox-klipse-theme-0.0.1" =
  {
    host = repositories.clojars;
    path =
      "viebel/codox-klipse-theme/0.0.1/codox-klipse-theme-0.0.1";
    type = "jar";
    pom = {
      sha1 = "5e1a00ea2bbdfc8cae4083c41e12be5cf89c1449";
      sha256 = "1qxd30dl06yahcgqnypnc71mhqzijpmnq9imybbkbvzk65i6y4r8";
    };
    jar = {
      sha1 = "09af0b348e6253dcf9fd567d0d22ffebdea46176";
      sha256 = "1qg2iyblykfkzmplc2c46916b9m0h5ad6lxmvrk5qn3pdxqr8vw0";
    };
  };
  "https://repo1.maven.org/maven2/args4j/args4j-site/2.0.26/args4j-site-2.0.26" =
  {
    host = repositories.maven;
    path =
      "args4j/args4j-site/2.0.26/args4j-site-2.0.26";
    type = "jar";
    pom = {
      sha1 = "d0b339416cfaa4ea16ddb0cd92711a8518892778";
      sha256 = "07icb97h7883z9mc5xdzlj31knymx8cqbpvvl6yajrrkbymis2hi";
    };
  };
  "https://repo1.maven.org/maven2/args4j/args4j-site/2.33/args4j-site-2.33" =
  {
    host = repositories.maven;
    path =
      "args4j/args4j-site/2.33/args4j-site-2.33";
    type = "jar";
    pom = {
      sha1 = "09ba12fde00306694af3ce9f5ff302c858345edf";
      sha256 = "1vqqdkrnrbkgxad1sw4qwxqw6rvv86r93ndwakggdg1y5v869ggj";
    };
  };
  "https://repo1.maven.org/maven2/args4j/args4j/2.0.26/args4j-2.0.26" =
  {
    host = repositories.maven;
    path =
      "args4j/args4j/2.0.26/args4j-2.0.26";
    type = "jar";
    pom = {
      sha1 = "f0aada195340b361a1a45aa9c3d417c7cbb0a6b5";
      sha256 = "0151vnbmbjnr5089ik8np91r3a4g2ylcahih22zr49a3ilri6f80";
    };
    jar = {
      sha1 = "01ebb18ebb3b379a74207d5af4ea7c8338ebd78b";
      sha256 = "193i0xgn295bdz5gk4zrk4ncfa29x8vl97bfd01kl1za44ixm6wq";
    };
  };
  "https://repo1.maven.org/maven2/args4j/args4j/2.33/args4j-2.33" =
  {
    host = repositories.maven;
    path =
      "args4j/args4j/2.33/args4j-2.33";
    type = "jar";
    pom = {
      sha1 = "168b592340292d4410a1d000bb7fa7144967fc12";
      sha256 = "046pab6gz1bh6w1jfbabgxvkrnvncrj93lnmaya5qs6a1z7mccn2";
    };
    jar = {
      sha1 = "bd87a75374a6d6523de82fef51fc3cfe9baf9fc9";
      sha256 = "1mlyqrqyhijwkjx4sv2zfn2ciqfwpc08qq8w55rcxb941fxfmpci";
    };
  };
  "https://repo1.maven.org/maven2/com/cognitect/transit-clj/0.8.309/transit-clj-0.8.309" =
  {
    host = repositories.maven;
    path =
      "com/cognitect/transit-clj/0.8.309/transit-clj-0.8.309";
    type = "jar";
    pom = {
      sha1 = "f6a2b94615ba4dcbdf1426bde259d3f628b5a54e";
      sha256 = "02m4bacn151xw4hy0bp7hrknx36jqs92mq3vjj30d5fgwxhsspgx";
    };
    jar = {
      sha1 = "24a39fe859effa9cdbb2c9f0e7e25856b41039ce";
      sha256 = "02p1ahm699gxddxg2avggxfs588n85cl4p29qqg0ks6n1cxiwv5c";
    };
  };
  "https://repo1.maven.org/maven2/com/cognitect/transit-java/0.8.332/transit-java-0.8.332" =
  {
    host = repositories.maven;
    path =
      "com/cognitect/transit-java/0.8.332/transit-java-0.8.332";
    type = "jar";
    pom = {
      sha1 = "e277700b7534c9e063290ad7518d2c7ce740c455";
      sha256 = "1sicl0hjr2fv1gid121blj42giybyc1gj1v90v2m866cmkpzi20w";
    };
    jar = {
      sha1 = "f76e5dced124be411e246e61c33db10b3005b881";
      sha256 = "02y1hi3pqjwxh4gk723lhbyrzfa7l78s09b4qhrhqg8mvigsbdla";
    };
  };
  "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.8.7/jackson-core-2.8.7" =
  {
    host = repositories.maven;
    path =
      "com/fasterxml/jackson/core/jackson-core/2.8.7/jackson-core-2.8.7";
    type = "jar";
    pom = {
      sha1 = "2ffdd0e4f11359b9216dd8e19d051b246da6a29f";
      sha256 = "0nlbbnhyzcfnixhg76m4q9lrlb5v7gkxwymbhcwbw3rjarfl33qd";
    };
    jar = {
      sha1 = "8b46f39c78476fb848c81a49fa807a9e9506dddd";
      sha256 = "0imv9xnw8l8zmpl5fz70v04zdw75wp1x5r1y9wdjsadb310z6vr5";
    };
  };
  "https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-parent/2.8/jackson-parent-2.8" =
  {
    host = repositories.maven;
    path =
      "com/fasterxml/jackson/jackson-parent/2.8/jackson-parent-2.8";
    type = "jar";
    pom = {
      sha1 = "d020f5b079a7c1608b08f4f9bd76f73cb9b3a1be";
      sha256 = "0n4kppglr435ilgk3vxh3f58hsabw45nq8i8jz4c4a9s3969jl9v";
    };
  };
  "https://repo1.maven.org/maven2/com/fasterxml/oss-parent/27/oss-parent-27" =
  {
    host = repositories.maven;
    path =
      "com/fasterxml/oss-parent/27/oss-parent-27";
    type = "jar";
    pom = {
      sha1 = "77c5efd41e5c52f4f68c36eeb7fe3ccdf0119e53";
      sha256 = "1sxy16jh605l7hqlvqbch7aqyv3jhs5lcmlp4jqmg032zn4g7f5r";
    };
  };
  "https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9" =
  {
    host = repositories.maven;
    path =
      "com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9";
    type = "jar";
    pom = {
      sha1 = "67ea333a3244bc20a17d6f0c29498071dfa409fc";
      sha256 = "0fm9gfc8ris3mq3zp06ra8fks3f8mxj60vdnybp7lg8w668r3azy";
    };
    jar = {
      sha1 = "40719ea6961c0cb6afaeb6a921eaa1f6afd4cfdf";
      sha256 = "1vf98qdxy0l4v1f0mvqxz92ydrd29vpyczmv999q22m9xsh22mwh";
    };
  };
  "https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.1/jsr305-3.0.1" =
  {
    host = repositories.maven;
    path =
      "com/google/code/findbugs/jsr305/3.0.1/jsr305-3.0.1";
    type = "jar";
    pom = {
      sha1 = "d04690f71f3393e23f30998d9534365274fa5f9f";
      sha256 = "1khlag991h7326xsjnpx6hnyip5cwawsmxz6m20kkzavvihsfw21";
    };
    jar = {
      sha1 = "f7be08ec23c21485b9b5a1cf1654c2ec8c58168d";
      sha256 = "1k9zl76xi2nykixaynss2gk4h861zipdb9xl6q1br0ln4hscx1f8";
    };
  };
  "https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2" =
  {
    host = repositories.maven;
    path =
      "com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2";
    type = "jar";
    pom = {
      sha1 = "8d93cdf4d84d7e1de736df607945c6df0730a10f";
      sha256 = "1zldsximvzlag566i5r2i124d5vs2jw4brjy39hb4m5jy6yrv20r";
    };
    jar = {
      sha1 = "25ea2e8b0c338a877313bd4672d3fe056ea78f0d";
      sha256 = "1iyh53li6y4b8gp8bl52fagqp8iqrkp4rmwa5jb8f9izg2hd4skn";
    };
  };
  "https://repo1.maven.org/maven2/com/google/code/gson/gson-parent/2.7/gson-parent-2.7" =
  {
    host = repositories.maven;
    path =
      "com/google/code/gson/gson-parent/2.7/gson-parent-2.7";
    type = "jar";
    pom = {
      sha1 = "3e147803ee87007ec82a1f625a0034be35c9b8a8";
      sha256 = "0ar7wk4zrdlb56jywsk6v3cpji8cjsi3kzmcr061yc12fdrqq7l7";
    };
  };
  "https://repo1.maven.org/maven2/com/google/code/gson/gson/2.2.4/gson-2.2.4" =
  {
    host = repositories.maven;
    path =
      "com/google/code/gson/gson/2.2.4/gson-2.2.4";
    type = "jar";
    pom = {
      sha1 = "06252c690921ee1dc719594a5d4da1829194f8b3";
      sha256 = "106k9ynbhls8nkihxrhkj5033z7q2am6x1l98vffck4935flv65f";
    };
    jar = {
      sha1 = "a60a5e993c98c864010053cb901b7eab25306568";
      sha256 = "1yw7qszcw1dsh54q6wyksr5mbkz8mzs1q36hmjjn7qx9gk88qcn0";
    };
  };
  "https://repo1.maven.org/maven2/com/google/code/gson/gson/2.7/gson-2.7" =
  {
    host = repositories.maven;
    path =
      "com/google/code/gson/gson/2.7/gson-2.7";
    type = "jar";
    pom = {
      sha1 = "09f9e39f9b791aeb73ba428ad30872f1a703edb3";
      sha256 = "1phf2qksjf75ykwgp39189jdbqsn5zrmi07g8h522yxq0zn3cfbj";
    };
    jar = {
      sha1 = "751f548c85fa49f330cecbb1875893f971b33c4e";
      sha256 = "0clda1xrjfja969xsbrhc61ip588xvsi9k054kpd4cz1m5gfnhrd";
    };
  };
  "https://repo1.maven.org/maven2/com/google/errorprone/error_prone_annotations/2.0.18/error_prone_annotations-2.0.18" =
  {
    host = repositories.maven;
    path =
      "com/google/errorprone/error_prone_annotations/2.0.18/error_prone_annotations-2.0.18";
    type = "jar";
    pom = {
      sha1 = "8e0351439081cc11563b09019302926addadaa25";
      sha256 = "11w4193x21z1zzqhngmq60qxbc13xgmdq9b86v115xnnj9qi4i4i";
    };
    jar = {
      sha1 = "5f65affce1684999e2f4024983835efc3504012e";
      sha256 = "0sv5i2kyl7qbchcb786d1x2fq39zfsjvwglz343klmmzf3cglk6b";
    };
  };
  "https://repo1.maven.org/maven2/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3" =
  {
    host = repositories.maven;
    path =
      "com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3";
    type = "jar";
    pom = {
      sha1 = "02d1529fa92342313d1c98beb8ca261e36a2d319";
      sha256 = "1x9pfan53fjf9sg2lrwi6g2dvs2b99x8d7ka7in9kciw74fbi34m";
    };
    jar = {
      sha1 = "39b109f2cd352b2d71b52a3b5a1a9850e1dc304b";
      sha256 = "1y3zzjqxckrn39z5d4724lwhkb9fx94i0kb3gkhsjgf18yak5l03";
    };
  };
  "https://repo1.maven.org/maven2/com/google/errorprone/error_prone_annotations/2.3.1/error_prone_annotations-2.3.1" =
  {
    host = repositories.maven;
    path =
      "com/google/errorprone/error_prone_annotations/2.3.1/error_prone_annotations-2.3.1";
    type = "jar";
    pom = {
      sha1 = "19c878e6870c8382864dcc459de1c6bfe7f36e54";
      sha256 = "16l1kbc7wbisjmjvkfac854ddyql0b5smdxr2vz8wdms26vydp1y";
    };
    jar = {
      sha1 = "a6a2b2df72fd13ec466216049b303f206bd66c5d";
      sha256 = "0831h49f21znl7z8lkr2ikywwajdachgxva7zpj8sp7rl2d9998h";
    };
  };
  "https://repo1.maven.org/maven2/com/google/errorprone/error_prone_parent/2.0.18/error_prone_parent-2.0.18" =
  {
    host = repositories.maven;
    path =
      "com/google/errorprone/error_prone_parent/2.0.18/error_prone_parent-2.0.18";
    type = "jar";
    pom = {
      sha1 = "16ffdb67ed91d9d87a943a3127da3900d83cc81d";
      sha256 = "1i46saxm7vx68cdl9drxswqfjsaa2v0qayc13vqx81wv4xarj56g";
    };
  };
  "https://repo1.maven.org/maven2/com/google/errorprone/error_prone_parent/2.1.3/error_prone_parent-2.1.3" =
  {
    host = repositories.maven;
    path =
      "com/google/errorprone/error_prone_parent/2.1.3/error_prone_parent-2.1.3";
    type = "jar";
    pom = {
      sha1 = "fa65cf11b2b7e955eb3862eb01d5bae721e458c0";
      sha256 = "16r3zfxxcz6ldykibcs7r7qbvwc81dw7msg03nawx7rql4b2canm";
    };
  };
  "https://repo1.maven.org/maven2/com/google/errorprone/error_prone_parent/2.3.1/error_prone_parent-2.3.1" =
  {
    host = repositories.maven;
    path =
      "com/google/errorprone/error_prone_parent/2.3.1/error_prone_parent-2.3.1";
    type = "jar";
    pom = {
      sha1 = "a32c199defa0dcf9c42a32c26fec4d1fbb408e58";
      sha256 = "08y16fkxl49930d2bqmic90vw9v36f02jf38344csa8im3cjaxbn";
    };
  };
  "https://repo1.maven.org/maven2/com/google/google/1/google-1" =
  {
    host = repositories.maven;
    path =
      "com/google/google/1/google-1";
    type = "jar";
    pom = {
      sha1 = "c35a5268151b7a1bbb77f7ee94a950f00e32db61";
      sha256 = "10by4ybrjnl8zwfg4ca74d0gcl4p9l7dzlfb9iwxw7m325xb2vfd";
    };
  };
  "https://repo1.maven.org/maven2/com/google/guava/guava-parent/17.0/guava-parent-17.0" =
  {
    host = repositories.maven;
    path =
      "com/google/guava/guava-parent/17.0/guava-parent-17.0";
    type = "jar";
    pom = {
      sha1 = "f8ba48b925d1c925d0fc0379ffa14a06e44eb464";
      sha256 = "0ajka1xsh28sammy3zbx82mvxi3k19v5ks4x2xswglsiamc57flz";
    };
  };
  "https://repo1.maven.org/maven2/com/google/guava/guava-parent/18.0/guava-parent-18.0" =
  {
    host = repositories.maven;
    path =
      "com/google/guava/guava-parent/18.0/guava-parent-18.0";
    type = "jar";
    pom = {
      sha1 = "5398932a9ef2828eb9fc4f01e8d6cac626c219d2";
      sha256 = "0rmia42xirzgk3r2h1syzs7n7ib1nv84yzh87yizcmz7jn4crb54";
    };
  };
  "https://repo1.maven.org/maven2/com/google/guava/guava-parent/19.0/guava-parent-19.0" =
  {
    host = repositories.maven;
    path =
      "com/google/guava/guava-parent/19.0/guava-parent-19.0";
    type = "jar";
    pom = {
      sha1 = "21fa0d898121cc408c19b74e4305403c6cc45b23";
      sha256 = "041y3i7yjajiylka0p1w0lz0d78c8wmswjkfld6zf46zxi1zyxiv";
    };
  };
  "https://repo1.maven.org/maven2/com/google/guava/guava-parent/20.0/guava-parent-20.0" =
  {
    host = repositories.maven;
    path =
      "com/google/guava/guava-parent/20.0/guava-parent-20.0";
    type = "jar";
    pom = {
      sha1 = "7ba07b80563d9b18c4d384600a6fc1792d7899dd";
      sha256 = "1w9dd5n0dsbl7br4gifb04d3m20xyc5sgprb4gbghan7gz86y8pi";
    };
  };
  "https://repo1.maven.org/maven2/com/google/guava/guava-parent/25.1-jre/guava-parent-25.1-jre" =
  {
    host = repositories.maven;
    path =
      "com/google/guava/guava-parent/25.1-jre/guava-parent-25.1-jre";
    type = "jar";
    pom = {
      sha1 = "802065dc15ff936f7c040c339111793dafcf02f0";
      sha256 = "13lngz2c4hzrdmazkxx511ak8nyq0xcydf4qqpn7gz4vvii6glf0";
    };
  };
  "https://repo1.maven.org/maven2/com/google/guava/guava/17.0/guava-17.0" =
  {
    host = repositories.maven;
    path =
      "com/google/guava/guava/17.0/guava-17.0";
    type = "jar";
    pom = {
      sha1 = "0f534dabee0b40b25715869c5e1287e38c7e1e4a";
      sha256 = "0nxpdkb27m770j0c4xlg7l34aj87h7qja7dbmqrcf99q1l0ic39a";
    };
    jar = {
      sha1 = "9c6ef172e8de35fd8d4d8783e4821e57cdef7445";
      sha256 = "1g7bhyvzsx61lrca01hvpivkdgjvgj1wy5qa0jwbdl0klq7ahdlc";
    };
  };
  "https://repo1.maven.org/maven2/com/google/guava/guava/18.0/guava-18.0" =
  {
    host = repositories.maven;
    path =
      "com/google/guava/guava/18.0/guava-18.0";
    type = "jar";
    pom = {
      sha1 = "2ec12f8d27a64e970b8be0fbd1d52dfec51cd41c";
      sha256 = "0dlqf4baf5h1j9b2a1i96n5l3i21vm7r3xync305sszpfqfxchz7";
    };
    jar = {
      sha1 = "cce0823396aa693798f8882e64213b1772032b09";
      sha256 = "16bgkzvk3sprn5rs9hfcpvz9vgyhy40zni1amffcxrfj0gygnr6n";
    };
  };
  "https://repo1.maven.org/maven2/com/google/guava/guava/19.0/guava-19.0" =
  {
    host = repositories.maven;
    path =
      "com/google/guava/guava/19.0/guava-19.0";
    type = "jar";
    pom = {
      sha1 = "65a43a21dbddcc19aa3ca50a63a4b33166bfbc77";
      sha256 = "0qxca62zgm95dqpgwx0v1n2r1mvwi2m5l3n99pgpy1zilx6hdp5d";
    };
    jar = {
      sha1 = "6ce200f6b23222af3d8abb6b6459e6c44f4bb0e9";
      sha256 = "1r3x0mznza3j1k3g75mhdz5y2fv2flph72snmjxi5c7b0lpcrm2q";
    };
  };
  "https://repo1.maven.org/maven2/com/google/guava/guava/20.0/guava-20.0" =
  {
    host = repositories.maven;
    path =
      "com/google/guava/guava/20.0/guava-20.0";
    type = "jar";
    pom = {
      sha1 = "386bd381301224cac5ae8d2c7883b90a12192d79";
      sha256 = "0xlhw5f82l4cw6qn85hw3ky4hvby8q4iwc6mcjjxfq5pcwvwhg1n";
    };
    jar = {
      sha1 = "89507701249388e1ed5ddcf8c41f4ce1be7831ef";
      sha256 = "1j48qav9slfmvyjhpxljs69nqvh8gsv58dm2vkqg1rqsnzind9in";
    };
  };
  "https://repo1.maven.org/maven2/com/google/guava/guava/25.1-jre/guava-25.1-jre" =
  {
    host = repositories.maven;
    path =
      "com/google/guava/guava/25.1-jre/guava-25.1-jre";
    type = "jar";
    pom = {
      sha1 = "5dd13f6c0d56f05059c5eba88a20a8699ece583d";
      sha256 = "1pya5f4vbh8z9zvprnl64i9qqp0rghjfsflx64q9md28w5pb9y35";
    };
    jar = {
      sha1 = "6c57e4b22b44e89e548b5c9f70f0c45fe10fb0b4";
      sha256 = "1gqaqxdnxhr1gk9haldrifvda8ingj1s4bin5sf455y38jic7c3d";
    };
  };
  "https://repo1.maven.org/maven2/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1" =
  {
    host = repositories.maven;
    path =
      "com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1";
    type = "jar";
    pom = {
      sha1 = "b964a9414771661bdf35a3f10692a2fb0dd2c866";
      sha256 = "1gnn7b80krv19qjd9hhacahffqq9iwqgmw4ds56wp9wk3rbqrjgh";
    };
    jar = {
      sha1 = "ed28ded51a8b1c6b112568def5f4b455e6809019";
      sha256 = "1xpcvmnw2y3fa56hhk8dmknrq8afr6r3kdmzsg9hnwgjg3msg519";
    };
  };
  "https://repo1.maven.org/maven2/com/google/javascript/closure-compiler-externs/v20150126/closure-compiler-externs-v20150126" =
  {
    host = repositories.maven;
    path =
      "com/google/javascript/closure-compiler-externs/v20150126/closure-compiler-externs-v20150126";
    type = "jar";
    pom = {
      sha1 = "c97211f4ef41140fa709e2a68b51b75f05bdb5e6";
      sha256 = "0dd4831sxz89gq6bsq0xmy6kpzmv80ikv7akirggv1r04h5yjvyq";
    };
    jar = {
      sha1 = "0153721bc5cefa99eabbf6cef22972774895ddd6";
      sha256 = "08l32yy6szkl1zl0gksmb2rh8sigmxjfpvh5vz0r0wl6kqiscnss";
    };
  };
  "https://repo1.maven.org/maven2/com/google/javascript/closure-compiler-externs/v20160911/closure-compiler-externs-v20160911" =
  {
    host = repositories.maven;
    path =
      "com/google/javascript/closure-compiler-externs/v20160911/closure-compiler-externs-v20160911";
    type = "jar";
    pom = {
      sha1 = "7b7a22dd2f7d760272db367cc58610f4fae3e3f9";
      sha256 = "1l9lg1sf1y4dpykx40rc6wsny3nwqjz69kpbxw15mc9yd0j5qlbp";
    };
    jar = {
      sha1 = "3186e2c9a2018bb49547947d2919b0e6998a1fe2";
      sha256 = "1dq7jg1cjx5f8d9rs72s5sc2rg2lslram9zp1nm9dxjpvfx47ihp";
    };
  };
  "https://repo1.maven.org/maven2/com/google/javascript/closure-compiler-externs/v20170521/closure-compiler-externs-v20170521" =
  {
    host = repositories.maven;
    path =
      "com/google/javascript/closure-compiler-externs/v20170521/closure-compiler-externs-v20170521";
    type = "jar";
    pom = {
      sha1 = "ad5a7758c46ed0361e1eedcbe6cd9bcfd953adc8";
      sha256 = "004ij8z6qcayv5rmllblckhr3idm9zrk75lkzlpbw83pxb43m2fv";
    };
    jar = {
      sha1 = "d838c1b40a31efac71687aa197ce559f5459f983";
      sha256 = "13yy2h4f9wbhilqw2sd7q3mgqmrpnlmwwhfg9nchkkz72rp5va97";
    };
  };
  "https://repo1.maven.org/maven2/com/google/javascript/closure-compiler-externs/v20190325/closure-compiler-externs-v20190325" =
  {
    host = repositories.maven;
    path =
      "com/google/javascript/closure-compiler-externs/v20190325/closure-compiler-externs-v20190325";
    type = "jar";
    pom = {
      sha1 = "016ecee910c8dc4d0295e60a5e3a1e8590539815";
      sha256 = "0bjxjdwdqmp3k55b5jr9i8mychsfsg5ky5vya9rn7jqs6wz5ympk";
    };
    jar = {
      sha1 = "410c1ae0585d36fbd12503b99b783f692c455519";
      sha256 = "0qnymibhmb76c5crm3yz71j5gmsjh041bj7mv4a1qsc4p5v7zh54";
    };
  };
  "https://repo1.maven.org/maven2/com/google/javascript/closure-compiler-main/v20160911/closure-compiler-main-v20160911" =
  {
    host = repositories.maven;
    path =
      "com/google/javascript/closure-compiler-main/v20160911/closure-compiler-main-v20160911";
    type = "jar";
    pom = {
      sha1 = "aba7ccec34a9c07ee7cc8d606bd2852f00ca9a9e";
      sha256 = "0bzzwassbwfqpqjvnggn26r53mg9ayw0w8paj4vbd9mqq1b1qg41";
    };
  };
  "https://repo1.maven.org/maven2/com/google/javascript/closure-compiler-main/v20170521/closure-compiler-main-v20170521" =
  {
    host = repositories.maven;
    path =
      "com/google/javascript/closure-compiler-main/v20170521/closure-compiler-main-v20170521";
    type = "jar";
    pom = {
      sha1 = "497c375aa4ea7deebab96e993b659a6b62926e41";
      sha256 = "0c9daw25c559h68vhfxjnk5gbv1z8yqx230r6q3ziff0fcpsc85q";
    };
  };
  "https://repo1.maven.org/maven2/com/google/javascript/closure-compiler-main/v20190325/closure-compiler-main-v20190325" =
  {
    host = repositories.maven;
    path =
      "com/google/javascript/closure-compiler-main/v20190325/closure-compiler-main-v20190325";
    type = "jar";
    pom = {
      sha1 = "2e57c608a83054269602ca875393588376bdae92";
      sha256 = "16dlvc62kg5kw00h02v35cpzfnjv6jl0l1sf4j6k2hv0zn688kih";
    };
  };
  "https://repo1.maven.org/maven2/com/google/javascript/closure-compiler-parent/v20150126/closure-compiler-parent-v20150126" =
  {
    host = repositories.maven;
    path =
      "com/google/javascript/closure-compiler-parent/v20150126/closure-compiler-parent-v20150126";
    type = "jar";
    pom = {
      sha1 = "0ad8953ef437e516f8782f7d28c0c3c71029c547";
      sha256 = "0wnhrmdf1pijs46vm4fdpd8qrkwa9lay1v2gs41bm77jir1q7l7y";
    };
  };
  "https://repo1.maven.org/maven2/com/google/javascript/closure-compiler-parent/v20151216/closure-compiler-parent-v20151216" =
  {
    host = repositories.maven;
    path =
      "com/google/javascript/closure-compiler-parent/v20151216/closure-compiler-parent-v20151216";
    type = "jar";
    pom = {
      sha1 = "df33701c6a148f90a5bd70c58278a1822736799a";
      sha256 = "1ji6lzs7bxcgdhdcyx2vlh84mzshfdlpm0nc6gmkqm7xf96i7k92";
    };
  };
  "https://repo1.maven.org/maven2/com/google/javascript/closure-compiler-parent/v20160911/closure-compiler-parent-v20160911" =
  {
    host = repositories.maven;
    path =
      "com/google/javascript/closure-compiler-parent/v20160911/closure-compiler-parent-v20160911";
    type = "jar";
    pom = {
      sha1 = "103384ce0cf44301a5e85b262ae7807142427b3e";
      sha256 = "0wmanmgpdl7p0bkbli4yn5pxz2w8jpljh0w84acn4f421nyd8cjg";
    };
  };
  "https://repo1.maven.org/maven2/com/google/javascript/closure-compiler-parent/v20170521/closure-compiler-parent-v20170521" =
  {
    host = repositories.maven;
    path =
      "com/google/javascript/closure-compiler-parent/v20170521/closure-compiler-parent-v20170521";
    type = "jar";
    pom = {
      sha1 = "a8720026489578de0b2d22806bffd55721eab378";
      sha256 = "0s6860ypm0m34qg0fbs5b2mg6zj5ff3sfs900l7n4n06dk1854qy";
    };
  };
  "https://repo1.maven.org/maven2/com/google/javascript/closure-compiler-parent/v20190325/closure-compiler-parent-v20190325" =
  {
    host = repositories.maven;
    path =
      "com/google/javascript/closure-compiler-parent/v20190325/closure-compiler-parent-v20190325";
    type = "jar";
    pom = {
      sha1 = "ab85e2babd5e00155da30883acbbf2d1e4f28b38";
      sha256 = "1kp3w6rw13avpsnkgg2d8k245yg9k9sf1hckdd8hidrzpv0v1qgz";
    };
  };
  "https://repo1.maven.org/maven2/com/google/javascript/closure-compiler-unshaded/v20160911/closure-compiler-unshaded-v20160911" =
  {
    host = repositories.maven;
    path =
      "com/google/javascript/closure-compiler-unshaded/v20160911/closure-compiler-unshaded-v20160911";
    type = "jar";
    pom = {
      sha1 = "9717f0d1134a13d075662d404f92fefc72ec9cbd";
      sha256 = "1rz1cpbaa1xilgp86kyj1dh6b3a2nxj3nvzlbliq6sgxvnvwp8s4";
    };
    jar = {
      sha1 = "96ac7a8c32377690555ac93310498bebea3e26ef";
      sha256 = "0s1d1cdb596gh1qzhqzp8i0r1mmmsp98cfajmsm5nljlyi5kd11a";
    };
  };
  "https://repo1.maven.org/maven2/com/google/javascript/closure-compiler-unshaded/v20170521/closure-compiler-unshaded-v20170521" =
  {
    host = repositories.maven;
    path =
      "com/google/javascript/closure-compiler-unshaded/v20170521/closure-compiler-unshaded-v20170521";
    type = "jar";
    pom = {
      sha1 = "9417f990267419490d14b93151f5cb83dd66440c";
      sha256 = "183i1ygpqhlqjfj38fdzpn3vfnhzwkj06yr1xbw6368xbv1hdivp";
    };
    jar = {
      sha1 = "8987aa201a79141369f8bfba77492093512f9dc4";
      sha256 = "1186iddh57ayy6x0r4zxjzj3w8f7vn2m132kc7bj1z8mf93337i6";
    };
  };
  "https://repo1.maven.org/maven2/com/google/javascript/closure-compiler-unshaded/v20190325/closure-compiler-unshaded-v20190325" =
  {
    host = repositories.maven;
    path =
      "com/google/javascript/closure-compiler-unshaded/v20190325/closure-compiler-unshaded-v20190325";
    type = "jar";
    pom = {
      sha1 = "2c2e9474bc0b5f7c0f8305265aaa43fca9bceb5a";
      sha256 = "0halaqpfgpjd9bbdrhyg1969d2zkr22vz1yz55jk69cy0yrz8b64";
    };
    jar = {
      sha1 = "d16b730974a39ed642991d1c11e9b2be37e6f709";
      sha256 = "0rzy3pccviy3psj064fqd4sb4b2riihrcwgv5r0lv6pm4hmx77mf";
    };
  };
  "https://repo1.maven.org/maven2/com/google/javascript/closure-compiler/v20150126/closure-compiler-v20150126" =
  {
    host = repositories.maven;
    path =
      "com/google/javascript/closure-compiler/v20150126/closure-compiler-v20150126";
    type = "jar";
    pom = {
      sha1 = "3e31c812c48c60de81b546647225b295120fa52e";
      sha256 = "0bmnadvdbpvrmmqh7j9avpcrj0xkvvxaikc0wgxpjfjddf512vca";
    };
    jar = {
      sha1 = "77122c57def78c9a0386fa600052d06d96a226a7";
      sha256 = "19pslgbv3il9ghdg68z8gwpg65hi85sbcmi9gnvm4pf83hfig2fc";
    };
  };
  "https://repo1.maven.org/maven2/com/google/javascript/closure-compiler/v20151216/closure-compiler-v20151216" =
  {
    host = repositories.maven;
    path =
      "com/google/javascript/closure-compiler/v20151216/closure-compiler-v20151216";
    type = "jar";
    pom = {
      sha1 = "b38b026d67c1086b15516e90f0cc99e9070e9c33";
      sha256 = "13dshdznvlplhhdabb4qb02d8mbq9k8ci2xacm2wwqcggl3nk5xp";
    };
    jar = {
      sha1 = "b5cd14a356cd9079791ba10b6d9623ef4ae4df6e";
      sha256 = "1wjnps06m015l1pzzzg9jmcvwz6dpjccz1c1ljbcbil9br4kprmv";
    };
  };
  "https://repo1.maven.org/maven2/com/google/jsinterop/jsinterop-annotations/1.0.0/jsinterop-annotations-1.0.0" =
  {
    host = repositories.maven;
    path =
      "com/google/jsinterop/jsinterop-annotations/1.0.0/jsinterop-annotations-1.0.0";
    type = "jar";
    pom = {
      sha1 = "2a76aa209ba1c76784db2f8cd00d98d349d2c909";
      sha256 = "00n35vbdh3j6ympsw0vppx1x6bs5bv4wg3a5mrnvbv408h68qnvd";
    };
    jar = {
      sha1 = "23c3a3c060ffe4817e67673cc8294e154b0a4a95";
      sha256 = "0m688mrv888fqszjnhhvv94pdfda3z61nr42sfinbywqxz7f1hg5";
    };
  };
  "https://repo1.maven.org/maven2/com/google/jsinterop/jsinterop/1.0.0/jsinterop-1.0.0" =
  {
    host = repositories.maven;
    path =
      "com/google/jsinterop/jsinterop/1.0.0/jsinterop-1.0.0";
    type = "jar";
    pom = {
      sha1 = "62210407b811fc7a4fe5edcf17b83f39b1e2dc01";
      sha256 = "1f7rzx53sdgagx0bx6gzym5d6a7wh6fhxkkzwkd2m83cas010x5k";
    };
  };
  "https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/2.5.0/protobuf-java-2.5.0" =
  {
    host = repositories.maven;
    path =
      "com/google/protobuf/protobuf-java/2.5.0/protobuf-java-2.5.0";
    type = "jar";
    pom = {
      sha1 = "d0b411e81d63761989f1329e8650ef27f6f77d25";
      sha256 = "0isgblny3w76jxiy7rdab3zg6d5f1sfw7vjal5y43al7mx97m0wx";
    };
    jar = {
      sha1 = "a10732c76bfacdbd633a7eb0f7968b1059a65dfa";
      sha256 = "0x6c4pbsizvk3lm6nxcgi1g2iqgrxcna1ip74lbn01f0fm2wdhg0";
    };
  };
  "https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.0.2/protobuf-java-3.0.2" =
  {
    host = repositories.maven;
    path =
      "com/google/protobuf/protobuf-java/3.0.2/protobuf-java-3.0.2";
    type = "jar";
    pom = {
      sha1 = "5dc19d1f724edfb259119a773d951935a1d72bfd";
      sha256 = "163skyjd62sphzq0wiv87q8k3hsard4803kqiw4jrfypyih615gx";
    };
    jar = {
      sha1 = "ee55e8e697d10b6643d77bb1f686bac3b9ba8579";
      sha256 = "0igpvapbbgkl5rmvf6li2c051676phipg9vf3gi7np7w7gzrs0ng";
    };
  };
  "https://repo1.maven.org/maven2/com/google/protobuf/protobuf-parent/3.0.2/protobuf-parent-3.0.2" =
  {
    host = repositories.maven;
    path =
      "com/google/protobuf/protobuf-parent/3.0.2/protobuf-parent-3.0.2";
    type = "jar";
    pom = {
      sha1 = "f00b6e9a0501e0d4870a76b8e877e3ec0d70dd00";
      sha256 = "0vzi1wh9d2x5qvfys2yhnf9pzlrgrmhmyyc2n5jqljzccm60ayhk";
    };
  };
  "https://repo1.maven.org/maven2/com/google/truth/truth-parent/0.24/truth-parent-0.24" =
  {
    host = repositories.maven;
    path =
      "com/google/truth/truth-parent/0.24/truth-parent-0.24";
    type = "jar";
    pom = {
      sha1 = "8f9907589a243fb3a610f55df12da1ae56709f4f";
      sha256 = "05m6hnqm0szsjhbncnpnnp3v8kcbgd48gsmi5z5x7lk27i6x1p9n";
    };
  };
  "https://repo1.maven.org/maven2/com/google/truth/truth/0.24/truth-0.24" =
  {
    host = repositories.maven;
    path =
      "com/google/truth/truth/0.24/truth-0.24";
    type = "jar";
    pom = {
      sha1 = "45149f71f8234d6c65a4478b5260edf00f5571c7";
      sha256 = "1261bpdnr2zdrv8z1qymhn9a5vpl6jh8vxhlqk4zm5dryylyfr9c";
    };
    jar = {
      sha1 = "7f70cea641f8812179c60162cb38354e81a459ae";
      sha256 = "1adv2cb5vbss4flx8q9z905nia031brnikk0szlryw7gkkxzj3pw";
    };
  };
  "https://repo1.maven.org/maven2/com/googlecode/java-diff-utils/diffutils/1.2.1/diffutils-1.2.1" =
  {
    host = repositories.maven;
    path =
      "com/googlecode/java-diff-utils/diffutils/1.2.1/diffutils-1.2.1";
    type = "jar";
    pom = {
      sha1 = "3db400baff3182027a58d7e1984974949f96c2a7";
      sha256 = "1p0cg71dj6d3q60ch1q5mpma824f7jakwpapbnc5i2f4frp6wl1a";
    };
    jar = {
      sha1 = "b716099bab8f2605aa3053824ece28f2b0ad1921";
      sha256 = "0wf1la6jsibrynrfsp2a7g2gx6f9q44v30qarm9m6x6xp31rg1n9";
    };
  };
  "https://repo1.maven.org/maven2/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1" =
  {
    host = repositories.maven;
    path =
      "com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1";
    type = "jar";
    pom = {
      sha1 = "5e902aae26ac5c36f6420f689f43333129dd69e2";
      sha256 = "10vzlnl8vbjv2jqf818wdb7kgy9c6qjka7fjmmi3vdpg1mcn6pv6";
    };
    jar = {
      sha1 = "c9ad4a0850ab676c5c64461a05ca524cdfff59f1";
      sha256 = "170rflxnqnah0265ik2aylmxkshyqbf2zas9bp2l32xqj9l6jsaf";
    };
  };
  "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.10/commons-codec-1.10" =
  {
    host = repositories.maven;
    path =
      "commons-codec/commons-codec/1.10/commons-codec-1.10";
    type = "jar";
    pom = {
      sha1 = "44b9477418d2942d45550f7e7c66c16262062d0e";
      sha256 = "1yscxabk7i59vgfjg7c1y3prj39h1d8prnwgxbisc4ni29qdpf5x";
    };
    jar = {
      sha1 = "4b95f4897fa13f2cd904aee711aeafc0c5295cd8";
      sha256 = "0scm6321zz76dc3bs8sy2qyami755lz4lq5455gl67bi9slxyha2";
    };
  };
  "https://repo1.maven.org/maven2/junit/junit/4.10/junit-4.10" =
  {
    host = repositories.maven;
    path =
      "junit/junit/4.10/junit-4.10";
    type = "jar";
    pom = {
      sha1 = "35bef83e80c3431f95d267e19252bddfe965041c";
      sha256 = "1d9fqsravgina2bn57dlvm3px7n54z7nw0nqg9mi1dp8m85vz892";
    };
    jar = {
      sha1 = "e4f1766ce7404a08f45d859fb9c226fc9e41a861";
      sha256 = "0nppn3pgsyh7py465nk6fxi0s0w7pciqfnq5i3mgd1hb3v54g9rn";
    };
  };
  "https://repo1.maven.org/maven2/org/apache/apache/15/apache-15" =
  {
    host = repositories.maven;
    path =
      "org/apache/apache/15/apache-15";
    type = "jar";
    pom = {
      sha1 = "95c70374817194cabfeec410fe70c3a6b832bafe";
      sha256 = "156lk89x31r2d6ljpwl1lvrl0sxgkd70wj6bq18b8rxcg7wz5hin";
    };
  };
  "https://repo1.maven.org/maven2/org/apache/apache/9/apache-9" =
  {
    host = repositories.maven;
    path =
      "org/apache/apache/9/apache-9";
    type = "jar";
    pom = {
      sha1 = "de55d73a30c7521f3d55e8141d360ffbdfd88caa";
      sha256 = "1p8qrz7swd6ylwfiv6x4kr3gip6sy2vca8xwydlxm3kwah5fcij9";
    };
  };
  "https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.3/commons-compress-1.3" =
  {
    host = repositories.maven;
    path =
      "org/apache/commons/commons-compress/1.3/commons-compress-1.3";
    type = "jar";
    pom = {
      sha1 = "b7d1722fa0f1bc04b7e8e41a31537a197c41bd6c";
      sha256 = "15mri91y6xy7qs0la1jp9qdvd5mlw25psqp2ngkchzih3kdsp88y";
    };
    jar = {
      sha1 = "613a08bc72e2e9a43c9f87b9ff8352b47e18e3ae";
      sha256 = "015aw9v4shj1hz1rbkiya06vc88czbx9pgsgng0aph7n4xa1laan";
    };
  };
  "https://repo1.maven.org/maven2/org/apache/commons/commons-parent/22/commons-parent-22" =
  {
    host = repositories.maven;
    path =
      "org/apache/commons/commons-parent/22/commons-parent-22";
    type = "jar";
    pom = {
      sha1 = "0e895fa7ed472b3b2081ef77e2d5ece78c139d54";
      sha256 = "1frwdic537d95l0ikgkvfpb4wjfjx2h5h211zysdsyhawdamx37v";
    };
  };
  "https://repo1.maven.org/maven2/org/apache/commons/commons-parent/35/commons-parent-35" =
  {
    host = repositories.maven;
    path =
      "org/apache/commons/commons-parent/35/commons-parent-35";
    type = "jar";
    pom = {
      sha1 = "d88c24ebb385e5404f34573f24362b17434e3f33";
      sha256 = "16p48k5ly6yli1wlzb5qcipwd0lzhsnbrjr1vk4x9v1nhfms363h";
    };
  };
  "https://repo1.maven.org/maven2/org/checkerframework/checker-qual/2.0.0/checker-qual-2.0.0" =
  {
    host = repositories.maven;
    path =
      "org/checkerframework/checker-qual/2.0.0/checker-qual-2.0.0";
    type = "jar";
    pom = {
      sha1 = "17ab37f0fb0338647a70ab40f15c2c685e4185e3";
      sha256 = "0s0062lnqk8vq23dil7qma7rl5x1h16h2x4bah7fw6rbvm9h7cfy";
    };
    jar = {
      sha1 = "518929596ee3249127502a8573b2e008e2d51ed3";
      sha256 = "15br88i0dk5l0hdh6ikgg6kvdbdir38jdw69j9s579az5xil317w";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/clojure/1.10.0/clojure-1.10.0" =
  {
    host = repositories.maven;
    path =
      "org/clojure/clojure/1.10.0/clojure-1.10.0";
    type = "jar";
    pom = {
      sha1 = "0dcfdfad678f6f603d178f895af86b82b040d69d";
      sha256 = "13434kg8sbnjy66ra3h8cv9l8ysb683w0j7fpay0q935hv52w390";
    };
    jar = {
      sha1 = "0383381021e03691dff101a9b12accb79e9a4e10";
      sha256 = "0f5fpgm2858jq5waq5ww1vvv44b5agi4vmnbhbgnwmy0b150j52h";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/clojure/1.10.1/clojure-1.10.1" =
  {
    host = repositories.maven;
    path =
      "org/clojure/clojure/1.10.1/clojure-1.10.1";
    type = "jar";
    pom = {
      sha1 = "3fc51cbb6dc8bb6fefc2bae63da919ae7e3d538e";
      sha256 = "131sv1nv3s0mpfv3bplh1z0b6hh7m403x00sxn236iqfz8jazxqh";
    };
    jar = {
      sha1 = "a1e6b92ce9b1bfc5d181867a45da8a38a6077662";
      sha256 = "06nj99mi0092qhv32ipk0nws4sdhnc890xx4gsgabllyzn8zkxnl";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/clojure/1.3.0/clojure-1.3.0" =
  {
    host = repositories.maven;
    path =
      "org/clojure/clojure/1.3.0/clojure-1.3.0";
    type = "jar";
    pom = {
      sha1 = "db857140ab8989f1eb286fc54315a8ccd19888ef";
      sha256 = "1akvgwybj3584mn4jg1i7xzp0gk5bng6jkf8ahxhxwyd1jl2np37";
    };
    jar = {
      sha1 = "04830e76a9e8c029acb257a70c5cf30592e5a301";
      sha256 = "0bmbc36mjdf4yxi9di0dsxkq04gwc9k1c2qzv44hdibi22sbzszp";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/clojure/1.4.0/clojure-1.4.0" =
  {
    host = repositories.maven;
    path =
      "org/clojure/clojure/1.4.0/clojure-1.4.0";
    type = "jar";
    pom = {
      sha1 = "7a8a4b7f3be166e9e7a6efb997bd750af5ab37fb";
      sha256 = "08fbsgm3qpdyqxr3w10q1g4diqvf5zjb9a4gpkgs9mvky29ad6zz";
    };
    jar = {
      sha1 = "867288bc07a6514e2e0b471c5be0bccd6c3a51f9";
      sha256 = "1j6ndg13f47f8r2vbkipq0yvhq2gc737xxkw7vccm50jqv4l0pjc";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/clojure/1.5.0/clojure-1.5.0" =
  {
    host = repositories.maven;
    path =
      "org/clojure/clojure/1.5.0/clojure-1.5.0";
    type = "jar";
    pom = {
      sha1 = "1a22da8c0a7a0406393182a6e20a262ea8cbfe2f";
      sha256 = "0wcan4qxs4fxq32c9xhmp3jn47clarnm4968l0nq1r1xvivrfnf4";
    };
    jar = {
      sha1 = "60fa560263212980c37bdc46da8ae41e6b9f6d7b";
      sha256 = "14briy542vysa2i60hn2qkqm4di3vh7vx5n5rg8i5wz6k3rc103s";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/clojure/1.5.1/clojure-1.5.1" =
  {
    host = repositories.maven;
    path =
      "org/clojure/clojure/1.5.1/clojure-1.5.1";
    type = "jar";
    pom = {
      sha1 = "d6fc44f6701fa2e0ed716551fab6eb57611ac378";
      sha256 = "1b2rdy98rmv5rl8576j09prh0aa268wvz0gd7482702bfadfhy3x";
    };
    jar = {
      sha1 = "e7e53da8bc4ac41fca95ccfacf84f9469dd3147f";
      sha256 = "078mrlsqgapvqwbp0yncjqilphsq7g366j3fck0bz8fyfzwq9h84";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/clojure/1.7.0-beta1/clojure-1.7.0-beta1" =
  {
    host = repositories.maven;
    path =
      "org/clojure/clojure/1.7.0-beta1/clojure-1.7.0-beta1";
    type = "jar";
    pom = {
      sha1 = "1439bf60e055332c636bfd9fd68e23b2104f4982";
      sha256 = "0glv5qdc0r3yrqwd8zyvqm2fsha2blhab88aiawbpf3m20gn89p9";
    };
    jar = {
      sha1 = "0b4d1297efd5fc8ffecb49e5b63f7af8e184f02d";
      sha256 = "106276vv0yzfnyaff5qsa8mqx8vrv00zyxjswdhbf57ls1i9s80l";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/clojure/1.7.0/clojure-1.7.0" =
  {
    host = repositories.maven;
    path =
      "org/clojure/clojure/1.7.0/clojure-1.7.0";
    type = "jar";
    pom = {
      sha1 = "809286a504011ff0556a3058533cf70ef15d4ae5";
      sha256 = "0zsbr4snlh6g5q9r97s1lyyxf2wr88r80gr8dnmynw7za7nrcwjz";
    };
    jar = {
      sha1 = "4953eb1ffa4adca22760c9324c9c26d2038c392a";
      sha256 = "1kjviqpwkf8cncjvdxdygh0ycf7x6rwd6g8y99cjm53hj46fr2af";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/clojure/1.8.0/clojure-1.8.0" =
  {
    host = repositories.maven;
    path =
      "org/clojure/clojure/1.8.0/clojure-1.8.0";
    type = "jar";
    pom = {
      sha1 = "54b0fc7541f1e399682fb20885fd558bd1c6a47f";
      sha256 = "1r0n01qzkfjb2dikfjll5i8g9nv087rwaarxmzp1ny3w3ny15ggz";
    };
    jar = {
      sha1 = "313066c972b6b00f390674bf0e9f732c07f205a4";
      sha256 = "1a30sdpn1rr50w7qfz6pn3z5i43fjq3z9qm1aa4cd9piwhgpy6h6";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/clojurescript/0.0-3211/clojurescript-0.0-3211" =
  {
    host = repositories.maven;
    path =
      "org/clojure/clojurescript/0.0-3211/clojurescript-0.0-3211";
    type = "jar";
    pom = {
      sha1 = "ee91448cb07065355725a7240b381e146b41c744";
      sha256 = "1ba99ljsdgfhwijgb40lb1w7gviy18a4vjklcwnkraw25bmxxj70";
    };
    jar = {
      sha1 = "607c611badd143a5f96ca1a0ecddd4c4e29e139e";
      sha256 = "1q9v5ni61aifxj24l4pjsfy1wlxak8nr0c4vmyajzwijgndml94s";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/clojurescript/1.10.520/clojurescript-1.10.520" =
  {
    host = repositories.maven;
    path =
      "org/clojure/clojurescript/1.10.520/clojurescript-1.10.520";
    type = "jar";
    pom = {
      sha1 = "56a6d73308b616f495ba8f380488e70d4af41a11";
      sha256 = "0nzycmc6xj7ahdkv8172h59d9ihhkf4mv9kqf21ngyarvpv8i9yi";
    };
    jar = {
      sha1 = "a0e637ee383cfd62a1f790929210efb2e372a9ce";
      sha256 = "029jz9x9pn3ayjzzy3ybikqzz4mv30v6znc6bw5qzch7qayqd425";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/clojurescript/1.7.228/clojurescript-1.7.228" =
  {
    host = repositories.maven;
    path =
      "org/clojure/clojurescript/1.7.228/clojurescript-1.7.228";
    type = "jar";
    pom = {
      sha1 = "2a0105d3425b7cc191548104b04248c49da08985";
      sha256 = "0fi24vi6xm7bw6b210m9pb5ijywq070mmkxajvy3h6w0gmzqgggz";
    };
    jar = {
      sha1 = "238989ea628e89499d1da64e231692bd2072d610";
      sha256 = "0z531izb085jnhiklmr8favvs154dnls5g3jm1nl1c99jd4b4g3g";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/clojurescript/1.9.293/clojurescript-1.9.293" =
  {
    host = repositories.maven;
    path =
      "org/clojure/clojurescript/1.9.293/clojurescript-1.9.293";
    type = "jar";
    pom = {
      sha1 = "f9ed2ec4f18bd09ce9fdc925be71facf80627501";
      sha256 = "04hh02a9fzyls51ylrzwjhzli256ds4n308nvz3vah515kbghzbp";
    };
    jar = {
      sha1 = "9916db845e309c7a62caeaa2f71bce4ae878459b";
      sha256 = "0blzqzdm7l9jsalz6ph8csdx287i1v3vmj684ffdfdaw38l6nriq";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/clojurescript/1.9.655/clojurescript-1.9.655" =
  {
    host = repositories.maven;
    path =
      "org/clojure/clojurescript/1.9.655/clojurescript-1.9.655";
    type = "jar";
    pom = {
      sha1 = "0e64057c4ae00ce24d9a143f0c8b1986038890a7";
      sha256 = "1schprif3llc37b2vhca33mf03zd5ib9ahjrqnibbp20mw0zlzc2";
    };
    jar = {
      sha1 = "7886fa49bdc8a886f0a6ba6790f04d5139a2cf38";
      sha256 = "0w62l7i875zim6ac5b0vhy98lgkkjj5jwfa5cjzvlyrz2j9ivld7";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/core.async/0.4.474/core.async-0.4.474" =
  {
    host = repositories.maven;
    path =
      "org/clojure/core.async/0.4.474/core.async-0.4.474";
    type = "jar";
    pom = {
      sha1 = "7ad313a6e7248eb4a52739dc13ff79b96ce15dd3";
      sha256 = "06xpvfrfh86lvqqa3jggrr8bzwaivfab15f0x1c1rgb0yblmip5z";
    };
    jar = {
      sha1 = "6887af0e03c4576855ea3dcda1c64947bef11569";
      sha256 = "1i7b87in8pw1can91lzxhjw23m7hn4ak5lwxcc4wvg4w7d6iqlpy";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/core.cache/0.6.5/core.cache-0.6.5" =
  {
    host = repositories.maven;
    path =
      "org/clojure/core.cache/0.6.5/core.cache-0.6.5";
    type = "jar";
    pom = {
      sha1 = "92272d3ea338358b51c62d6c5fdbae51f37c46c4";
      sha256 = "0yzljp1lmy757bavm66yycw12rg8fxbkir4zysy9g5ywy7757bc2";
    };
    jar = {
      sha1 = "82e7ab47bec2f7713817ff46c0150fc89ec20ff9";
      sha256 = "0i4bkwpqd7r6hcq5j5y6pjw8jbkym50zvnnrvl924gc20fjg06ll";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/core.memoize/0.5.9/core.memoize-0.5.9" =
  {
    host = repositories.maven;
    path =
      "org/clojure/core.memoize/0.5.9/core.memoize-0.5.9";
    type = "jar";
    pom = {
      sha1 = "b1319c4e147f67fdeda645fa398938201dd563e4";
      sha256 = "13h6q34mh7m7bb4wydq25pp56gk0a91j06k8pldbnyynh5ydkqwk";
    };
    jar = {
      sha1 = "cb8bd16034be49ecb95eb29d06a314294949674a";
      sha256 = "1dqi2q6g1p2kf2ypqx22dgrscvkad98fv4ijf00cxfn4wvp7hykr";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/core.specs.alpha/0.2.44/core.specs.alpha-0.2.44" =
  {
    host = repositories.maven;
    path =
      "org/clojure/core.specs.alpha/0.2.44/core.specs.alpha-0.2.44";
    type = "jar";
    pom = {
      sha1 = "5626897d1c41a6374c995a296789818a499b8804";
      sha256 = "11m6k5bm8yzrhr872i5y74iqynhw6z4m7y9ff08kzrfqr5k7plwd";
    };
    jar = {
      sha1 = "6027ceb1d1ae70a6a3fb1a8da2144632fa688604";
      sha256 = "071q9dvp9nn3fkqs9yc27kgnmddkps1r0w22d3vipr78y3bc87iv";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/data.json/0.2.6/data.json-0.2.6" =
  {
    host = repositories.maven;
    path =
      "org/clojure/data.json/0.2.6/data.json-0.2.6";
    type = "jar";
    pom = {
      sha1 = "6bcbbff673ad3df6c716e9ae91d8bbdd8f210c02";
      sha256 = "1bdp6b9zqhjvnfwswfgrxijdw478b4g0l824hc3qzhdigr8bymzw";
    };
    jar = {
      sha1 = "ac3437a78d08f9db3dac7debe5a069edac282d95";
      sha256 = "0x4r48mb4pk76ymhgmzhzwkghwcxn9lsp7p2dqdm4xv7rjfn2qkz";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/data.priority-map/0.0.7/data.priority-map-0.0.7" =
  {
    host = repositories.maven;
    path =
      "org/clojure/data.priority-map/0.0.7/data.priority-map-0.0.7";
    type = "jar";
    pom = {
      sha1 = "b9278c2a4882568d243166400d04f889615d760f";
      sha256 = "0j54r83bj4dakh0jfbjghdyf5qdkjjqg2kb11qc41bj1l46c0lvg";
    };
    jar = {
      sha1 = "ededdc5d68217ffa8d24ada18bae19c352b8521b";
      sha256 = "0yqcxi79xvjmr5i2dkq2l9c6h8x0xsqg7zj45shn54n2mw3pah38";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/google-closure-library-third-party/0.0-20140718-946a7d39/google-closure-library-third-party-0.0-20140718-946a7d39" =
  {
    host = repositories.maven;
    path =
      "org/clojure/google-closure-library-third-party/0.0-20140718-946a7d39/google-closure-library-third-party-0.0-20140718-946a7d39";
    type = "jar";
    pom = {
      sha1 = "700be6aba12dc30977e3dcbb44bedab5707487d4";
      sha256 = "1mb651kgln655gbp6yalf2s3y0iha1l6pmpzzvnr78vz3lha7rd8";
    };
    jar = {
      sha1 = "1faa3e7cc534b4d07ecfde8f2e7db86f76eaa015";
      sha256 = "0xqy9dyqg97gv4cap2fnhfx0frkvqqirj9lwhal6p8p8db8yk4bg";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/google-closure-library-third-party/0.0-20151016-61277aea/google-closure-library-third-party-0.0-20151016-61277aea" =
  {
    host = repositories.maven;
    path =
      "org/clojure/google-closure-library-third-party/0.0-20151016-61277aea/google-closure-library-third-party-0.0-20151016-61277aea";
    type = "jar";
    pom = {
      sha1 = "9ece8b0dc2754d0a49ee7fc07d83eda2105299d3";
      sha256 = "0x6l20zwms8j01kk3rv7q863nvx38m8s5q3ac7gydgbsnzmrpg2m";
    };
    jar = {
      sha1 = "aeb6a88cb9aeaa3641ed46aab036fb73035b2253";
      sha256 = "1mb3zvg3jimpjgcg1l6kq0imwp4b84zazd77qxszydp2jdcp7dhv";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/google-closure-library-third-party/0.0-20160609-f42b4a24/google-closure-library-third-party-0.0-20160609-f42b4a24" =
  {
    host = repositories.maven;
    path =
      "org/clojure/google-closure-library-third-party/0.0-20160609-f42b4a24/google-closure-library-third-party-0.0-20160609-f42b4a24";
    type = "jar";
    pom = {
      sha1 = "7fe7843f34ca567b80745a93f96af24761ab02d7";
      sha256 = "1b47a2slvl2k0rmsryf71qw31sc89ggcqh3inf5hdd11y7c4c3l7";
    };
    jar = {
      sha1 = "93ee501d8b971532e39c91af103e4e69988edbf8";
      sha256 = "1yhazjgz47075mbwj2951nlh28l1mhn6fz54z5vl4cpg3rwwif5i";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/google-closure-library-third-party/0.0-20170519-fa0499ef/google-closure-library-third-party-0.0-20170519-fa0499ef" =
  {
    host = repositories.maven;
    path =
      "org/clojure/google-closure-library-third-party/0.0-20170519-fa0499ef/google-closure-library-third-party-0.0-20170519-fa0499ef";
    type = "jar";
    pom = {
      sha1 = "fe9a6f9750910acf9475c0357bfbb2834921c91c";
      sha256 = "0wda27jfjkyzbabz1vvz5ki49x2wwd0c6xglap6m4rck43sdn8mm";
    };
    jar = {
      sha1 = "0c7805f1b0ebc5678c52d95065d8fad82d43e9ca";
      sha256 = "1vnpwkk5k89m6lyjs3k6hkks8b26j2gsfafq0f0f7dv7waj2rnjb";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/google-closure-library-third-party/0.0-20190213-2033d5d9/google-closure-library-third-party-0.0-20190213-2033d5d9" =
  {
    host = repositories.maven;
    path =
      "org/clojure/google-closure-library-third-party/0.0-20190213-2033d5d9/google-closure-library-third-party-0.0-20190213-2033d5d9";
    type = "jar";
    pom = {
      sha1 = "6acaef9c9891a4cef28796e49907f244ed356afe";
      sha256 = "0vr7786f9bjrm5bb9hr1iql68ld631zcgglak9z82xnlw877vx4c";
    };
    jar = {
      sha1 = "03b04d58baba7a54de05707a611f45b545063cda";
      sha256 = "1sg09m1siylp159w0z4p9wmxb8bqvkvymcr3yff1fk705knhhjnw";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/google-closure-library/0.0-20140718-946a7d39/google-closure-library-0.0-20140718-946a7d39" =
  {
    host = repositories.maven;
    path =
      "org/clojure/google-closure-library/0.0-20140718-946a7d39/google-closure-library-0.0-20140718-946a7d39";
    type = "jar";
    pom = {
      sha1 = "d23caa1fedbafd70f742c94c3573c3dda08b52b9";
      sha256 = "0n4s85kmkklw7mkc31lr7iklwyn5bywsnwl3dpa1mz49jgmn1hnd";
    };
    jar = {
      sha1 = "bc1127c9432ef876b813911f0333841e7076cab3";
      sha256 = "12yvwlcdg0djcddy7c7ck2bdczmfs25sf0njcj38r48pn4icry13";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/google-closure-library/0.0-20151016-61277aea/google-closure-library-0.0-20151016-61277aea" =
  {
    host = repositories.maven;
    path =
      "org/clojure/google-closure-library/0.0-20151016-61277aea/google-closure-library-0.0-20151016-61277aea";
    type = "jar";
    pom = {
      sha1 = "d70932bd3fc0d41c58769fdd2c4691ffe54a8bbe";
      sha256 = "1ifclhc3fj26izcicq9q0dljb4wp0g9k4wzg0syiynnvgklrih71";
    };
    jar = {
      sha1 = "b0693cbca3c96f464e6949c1a21cd8508d46b413";
      sha256 = "0v2mxg4vd58pzvdqypr4nkmaizk0fy55z10njr0ng0hrkcwp2z99";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/google-closure-library/0.0-20160609-f42b4a24/google-closure-library-0.0-20160609-f42b4a24" =
  {
    host = repositories.maven;
    path =
      "org/clojure/google-closure-library/0.0-20160609-f42b4a24/google-closure-library-0.0-20160609-f42b4a24";
    type = "jar";
    pom = {
      sha1 = "37f91f62279a48607153dfc435017398dde79fd0";
      sha256 = "0rpp5ksss6z7g0p5wgddpiny70jhg75v2mxy6asihc6v8k4xnfjh";
    };
    jar = {
      sha1 = "f5585ba44bdd8981eeaf24dfd7a16921f9278b8d";
      sha256 = "0ng60nf8fimnqmsp62pjgrqxfqv2m00qpzp6l7b3qhzibwgki18j";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/google-closure-library/0.0-20170519-fa0499ef/google-closure-library-0.0-20170519-fa0499ef" =
  {
    host = repositories.maven;
    path =
      "org/clojure/google-closure-library/0.0-20170519-fa0499ef/google-closure-library-0.0-20170519-fa0499ef";
    type = "jar";
    pom = {
      sha1 = "4720292600cf48ae2ab5e5423c16ed99372a2c09";
      sha256 = "0w1zjcxx3d895kw7zaw6j6d0f9c0g5r5ykrqam8qpmpz1sslw6hg";
    };
    jar = {
      sha1 = "a9060227c711e90c0564bfeab93570ee5aa839bf";
      sha256 = "00yxra6506kp58x86a88jn9sy4dr8w974daa7xrni5whafyyrgn0";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/google-closure-library/0.0-20190213-2033d5d9/google-closure-library-0.0-20190213-2033d5d9" =
  {
    host = repositories.maven;
    path =
      "org/clojure/google-closure-library/0.0-20190213-2033d5d9/google-closure-library-0.0-20190213-2033d5d9";
    type = "jar";
    pom = {
      sha1 = "d38f2cdfc2f40c2fe9cc9c63763260b22469b511";
      sha256 = "1ldqr4hkmvrdl9aqklmyy3d3sbm9mmhnnbnsj7wn6ha5cgka0929";
    };
    jar = {
      sha1 = "a1097a8a3353f0ef585ba7aa6caa68d8834254e1";
      sha256 = "1c1xl1bb2l1h6vbgqa25knd8ndbv159pakgjb04s2pripl3drpy8";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/pom.contrib/0.1.2/pom.contrib-0.1.2" =
  {
    host = repositories.maven;
    path =
      "org/clojure/pom.contrib/0.1.2/pom.contrib-0.1.2";
    type = "jar";
    pom = {
      sha1 = "5cb07d612649e2c48c4a3632e19541d37a44e23a";
      sha256 = "01l0zy2n7g42ffmq3dyznpkalnvgy53i65sqq8bqrfncin1vv026";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/pom.contrib/0.2.0/pom.contrib-0.2.0" =
  {
    host = repositories.maven;
    path =
      "org/clojure/pom.contrib/0.2.0/pom.contrib-0.2.0";
    type = "jar";
    pom = {
      sha1 = "e81260d61365da80b985560c53959810f90df42b";
      sha256 = "0yzfhfplfmf49njz1lg2vp86bmp316mgcqrmm0pvl8x7y52pfyic";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/pom.contrib/0.2.2/pom.contrib-0.2.2" =
  {
    host = repositories.maven;
    path =
      "org/clojure/pom.contrib/0.2.2/pom.contrib-0.2.2";
    type = "jar";
    pom = {
      sha1 = "ac4744d31d0752bc38a16d5945526fa845a1e2c1";
      sha256 = "08q3q72iwh37cv6aafp47ybxxr77gg2zq9ndah3y7hy595y25sp0";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/spec.alpha/0.2.176/spec.alpha-0.2.176" =
  {
    host = repositories.maven;
    path =
      "org/clojure/spec.alpha/0.2.176/spec.alpha-0.2.176";
    type = "jar";
    pom = {
      sha1 = "7e28eb2449d59217132147c19a80e0d3c8c2515f";
      sha256 = "14mj43w6lfqh68c7yx9rshchpjdzwl1nmmlwdavwhk2qgd3w1769";
    };
    jar = {
      sha1 = "cd2d5b03d2ff95a958cb075201b89d28a7dea626";
      sha256 = "1i3chggca910ln6h59ns17p454rpw55ffl6hgymx5p9lzzn9ckpw";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/tools.analyzer.jvm/0.7.0/tools.analyzer.jvm-0.7.0" =
  {
    host = repositories.maven;
    path =
      "org/clojure/tools.analyzer.jvm/0.7.0/tools.analyzer.jvm-0.7.0";
    type = "jar";
    pom = {
      sha1 = "e4de601a581040a5c5bdc2db708362dda32c060e";
      sha256 = "1dc40hvqgz2bhjdsgvck9iad4bbkma0j69qbsvdf3b20pdixdqh4";
    };
    jar = {
      sha1 = "51301d4c5320762cc287626b9e07d255fb9d3329";
      sha256 = "1s935mgzxfvaxyj4phf4lzqdp0b5bkiarxnb6ip1rk8anrdcapyd";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/tools.analyzer/0.6.9/tools.analyzer-0.6.9" =
  {
    host = repositories.maven;
    path =
      "org/clojure/tools.analyzer/0.6.9/tools.analyzer-0.6.9";
    type = "jar";
    pom = {
      sha1 = "d4a89aca74c79bce38710f79bd342ff1b7553aed";
      sha256 = "1yl5q79aw8mhxi4w5zh3ad9q8l0fqhgba86wk50hcaiv5w990fwq";
    };
    jar = {
      sha1 = "d16179b3993357015b306c34f2694c69cff93eb1";
      sha256 = "1cs6l541bpipwyd3mzm7xi0qw67hxniv4kacsb7c639jn75nbydk";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/tools.logging/0.4.1/tools.logging-0.4.1" =
  {
    host = repositories.maven;
    path =
      "org/clojure/tools.logging/0.4.1/tools.logging-0.4.1";
    type = "jar";
    pom = {
      sha1 = "483bbfc82aee3c005bb1ad36dec77ba5d6c5f95c";
      sha256 = "1qhfigr9am90fx527ax6f7z7xahgsd5hzb4pmi40n79nx3jsc9hf";
    };
    jar = {
      sha1 = "991bebc6e3633b85091ae929d62c116a2584aee7";
      sha256 = "001sx1ddgx0ys0z1qphzpxjf2w35rikrfjc0h5bvvqbw8ra0vvja";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/tools.namespace/0.2.11/tools.namespace-0.2.11" =
  {
    host = repositories.maven;
    path =
      "org/clojure/tools.namespace/0.2.11/tools.namespace-0.2.11";
    type = "jar";
    pom = {
      sha1 = "9ec25451fcbcf600e30e0303a20e6bf6d6dbf6db";
      sha256 = "1gnx92ibcprz86938742ygxv1rgk1ridlcxxf9bxks30p3ay4qr3";
    };
    jar = {
      sha1 = "d2c74b36d3d9b4a8d982c52001365885aabddba7";
      sha256 = "1bmdv2p581mw436s69zdyz0pdwn4czh7s59dfyqgbv8l0vkhnpqc";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/tools.reader/0.10.0/tools.reader-0.10.0" =
  {
    host = repositories.maven;
    path =
      "org/clojure/tools.reader/0.10.0/tools.reader-0.10.0";
    type = "jar";
    pom = {
      sha1 = "99754855cbbee3517e3ab263346539f897f7ceba";
      sha256 = "1v6fm8w7w18hpz21cyk38pgc0212g6d1ds8xmg8ag34kqbgv20fj";
    };
    jar = {
      sha1 = "33f708ca897d542008ab2bd0d35a27a6d160a1fc";
      sha256 = "04m8lcfkkcqbqn8bpjsg0p188jf56v9r73jxqg2csrzg6warmnip";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/tools.reader/0.9.1/tools.reader-0.9.1" =
  {
    host = repositories.maven;
    path =
      "org/clojure/tools.reader/0.9.1/tools.reader-0.9.1";
    type = "jar";
    pom = {
      sha1 = "e17e3ecd87bfcbe6a7640da24cef56eb5fc547b0";
      sha256 = "0r852i1wij514xkll2h1y5h6y1hgkg5wr84zwsczpgyxs5n18s7l";
    };
    jar = {
      sha1 = "4635d289ae80e7eccfc5377bbfb2f78d36bec23a";
      sha256 = "05az8g33kr5qva92akb7dr5a311wqmcqx0f5lpan1lc8312rm8g3";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/tools.reader/1.0.0-alpha1/tools.reader-1.0.0-alpha1" =
  {
    host = repositories.maven;
    path =
      "org/clojure/tools.reader/1.0.0-alpha1/tools.reader-1.0.0-alpha1";
    type = "jar";
    pom = {
      sha1 = "9a47527c35e0c359dcd917f2b61554dcd562aec8";
      sha256 = "09lgsa18imv6rzsib670r3mvrb0kjdwcx6ymhlxmb3jknzfg6pdp";
    };
    jar = {
      sha1 = "f0ef5ec2d46b638739b9e59a8f516b1b84b40bad";
      sha256 = "0s59lw79lx9b1sk08xg5518vzby49p7znpka93ir8kkxd4cd9566";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/tools.reader/1.0.0-alpha3/tools.reader-1.0.0-alpha3" =
  {
    host = repositories.maven;
    path =
      "org/clojure/tools.reader/1.0.0-alpha3/tools.reader-1.0.0-alpha3";
    type = "jar";
    pom = {
      sha1 = "333d98ad6e37d2db52bfc106287577fbd05ddb1b";
      sha256 = "10rk7fvbi2r4mvgmbzq1ch3v1pc76vhhylrszrrp58dpb6dx1xzz";
    };
    jar = {
      sha1 = "7ef609d39f462fe27140d0594ccf37d7c3356a4f";
      sha256 = "194166s2938w66mrlj1myj3l5pbdd23fcd5ijy9d1gscc6b6q5ga";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/tools.reader/1.0.0-alpha4/tools.reader-1.0.0-alpha4" =
  {
    host = repositories.maven;
    path =
      "org/clojure/tools.reader/1.0.0-alpha4/tools.reader-1.0.0-alpha4";
    type = "jar";
    pom = {
      sha1 = "097de81638713b15c4ad9d63adda0c296154142f";
      sha256 = "0lh2h5412ly9wg2x8xpg7azavmap2km1m0iiabygivib2n4rh08d";
    };
    jar = {
      sha1 = "579232c937d05dc6547b6dc7fabccca2773cc271";
      sha256 = "1ib07xdjc0s9509j2hxclrr5b1xdj28ypdas6scz1mvjamp5zwgp";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/tools.reader/1.0.0-beta3/tools.reader-1.0.0-beta3" =
  {
    host = repositories.maven;
    path =
      "org/clojure/tools.reader/1.0.0-beta3/tools.reader-1.0.0-beta3";
    type = "jar";
    pom = {
      sha1 = "4545cf22c703c03cbccd807171afef38c2431e75";
      sha256 = "0aycgp49zjakvlm3nk19g2jacamdg9givvlwnqa8fbakjpawcljf";
    };
    jar = {
      sha1 = "2551fe91105779f8641ed51d8eb21f1bf50b49e4";
      sha256 = "1g6p58rk8bfw7m5qbbx79j85hb9kn0df2wf8xnwwf5cmbpi3w4ns";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/tools.reader/1.0.0-beta4/tools.reader-1.0.0-beta4" =
  {
    host = repositories.maven;
    path =
      "org/clojure/tools.reader/1.0.0-beta4/tools.reader-1.0.0-beta4";
    type = "jar";
    pom = {
      sha1 = "419cc516e47f57930a1382501082130baf75cd0a";
      sha256 = "1f074jakaaibvyjqwcc6m2axka2ssh4b3wb17c22lx4i8bsc3rnd";
    };
    jar = {
      sha1 = "517ca01ba46f41bd67902836d024bcf717f25ef3";
      sha256 = "1i1lv2im3ds68s7rffa73xqsvvc51lw1rsmqlp6rsqfy1rvm81pf";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/tools.reader/1.0.0/tools.reader-1.0.0" =
  {
    host = repositories.maven;
    path =
      "org/clojure/tools.reader/1.0.0/tools.reader-1.0.0";
    type = "jar";
    pom = {
      sha1 = "fdc0f3839742d36e6c02422d4b583949ef7358bf";
      sha256 = "097rxp14ddvc06iycn9diym4fyif828f9832jnq489i4rplq7c91";
    };
    jar = {
      sha1 = "37d55284a058d65c3af9743c33819cb42cd20369";
      sha256 = "0g8jms9mn01i1ywjs9mr0069dg62fc2qpv2kc1ag41hy5fm8yflh";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/tools.reader/1.0.5/tools.reader-1.0.5" =
  {
    host = repositories.maven;
    path =
      "org/clojure/tools.reader/1.0.5/tools.reader-1.0.5";
    type = "jar";
    pom = {
      sha1 = "322cf7b44ea76dacd0aee9e8e7f450d2dfed26ed";
      sha256 = "152qffmilpf0bjxdqby1jryw5ly5708l9v4q66a65fakxkfjc6c8";
    };
    jar = {
      sha1 = "78fd57f3f979d32d0299dacb1f9461017caa3bb4";
      sha256 = "0sd75sgwxci248msszj0rqb9jmqmdd63cla8f9iqnqrq136h8gn2";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/tools.reader/1.2.1/tools.reader-1.2.1" =
  {
    host = repositories.maven;
    path =
      "org/clojure/tools.reader/1.2.1/tools.reader-1.2.1";
    type = "jar";
    pom = {
      sha1 = "6c5c027953ae14c36f79a4567d424ddd7a13bbab";
      sha256 = "1yyxa20a9bc2v2n2is0kr2n6ry1qm9mkzkhki22n51rqysdka94s";
    };
    jar = {
      sha1 = "b5009154208e51b76cebafa3b458e1f8a064adc9";
      sha256 = "1v2kdmn9cvjiyidp6z829w7fk6xaa2wp1x8v85lnzsxqg2a7chgn";
    };
  };
  "https://repo1.maven.org/maven2/org/clojure/tools.reader/1.3.0/tools.reader-1.3.0" =
  {
    host = repositories.maven;
    path =
      "org/clojure/tools.reader/1.3.0/tools.reader-1.3.0";
    type = "jar";
    pom = {
      sha1 = "cbf93ce8fbf66620f734275187d2aa0be9ea2639";
      sha256 = "0gzqr57p4qczm9dg028pnnsg0mfhg83b8ihvqxvgw6v74w5srkkw";
    };
    jar = {
      sha1 = "78c597e8e9922dbdbdabb192f7a49c6ee74fa480";
      sha256 = "0fjbk7d17chialnhq9n6ylhi1ah9hf04vxh6m1qlwxhdj6v9v00c";
    };
  };
  "https://repo1.maven.org/maven2/org/codehaus/codehaus-parent/4/codehaus-parent-4" =
  {
    host = repositories.maven;
    path =
      "org/codehaus/codehaus-parent/4/codehaus-parent-4";
    type = "jar";
    pom = {
      sha1 = "8b133202d50bec1e59bddc9392cb44d1fe5facc8";
      sha256 = "1pqlw2ilzagcl5ahq9dv60cxw59yrvrwf9q6z0679qf2x1yj71vb";
    };
  };
  "https://repo1.maven.org/maven2/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14" =
  {
    host = repositories.maven;
    path =
      "org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14";
    type = "jar";
    pom = {
      sha1 = "99a56e3312f8ece1d457c8ca0a3c4b69d173d000";
      sha256 = "09ianw2880ch3x6xq5d2cz2b15ik6f4ndf8hb7ckw7lr0ndg2y8q";
    };
    jar = {
      sha1 = "775b7e22fb10026eed3f86e8dc556dfafe35f2d5";
      sha256 = "0pchd4360mim0f0a6vwr33szigihgvv4ic1scz1l9mxssq5k4s10";
    };
  };
  "https://repo1.maven.org/maven2/org/codehaus/mojo/animal-sniffer-parent/1.14/animal-sniffer-parent-1.14" =
  {
    host = repositories.maven;
    path =
      "org/codehaus/mojo/animal-sniffer-parent/1.14/animal-sniffer-parent-1.14";
    type = "jar";
    pom = {
      sha1 = "c1e91a9c2f36d9e6d3c7087242d8d9ec56052e5d";
      sha256 = "1skf65rbw52shb2akgs7xykn06lj1ggp23nbc94vs40ldfh505gm";
    };
  };
  "https://repo1.maven.org/maven2/org/codehaus/mojo/mojo-parent/34/mojo-parent-34" =
  {
    host = repositories.maven;
    path =
      "org/codehaus/mojo/mojo-parent/34/mojo-parent-34";
    type = "jar";
    pom = {
      sha1 = "803dc5cf36e504c5a48aa9a321f7fba1d6396733";
      sha256 = "171a71yz4np2h0nlkm9zx82q6f97wm66kj6afhvrmh23pipmsf9y";
    };
  };
  "https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1" =
  {
    host = repositories.maven;
    path =
      "org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1";
    type = "jar";
    pom = {
      sha1 = "fe8b54d8729315853ee866322436df89aa8ab9ae";
      sha256 = "10vw86l86qg26dddmyplixmzr3413kncnz277x0cp3660vs8fwrr";
    };
    jar = {
      sha1 = "860340562250678d1a344907ac75754e259cdb14";
      sha256 = "1yygsl4nwzr1nzpr4iqkf9866807428ymvsr2f34zngh7x4x2q83";
    };
  };
  "https://repo1.maven.org/maven2/org/hamcrest/hamcrest-parent/1.1/hamcrest-parent-1.1" =
  {
    host = repositories.maven;
    path =
      "org/hamcrest/hamcrest-parent/1.1/hamcrest-parent-1.1";
    type = "jar";
    pom = {
      sha1 = "31ef4ab73bb6d6173f46ecf92d6bd9047516c6ca";
      sha256 = "0fkyq3bb04wlhmv5iwgncwqjgzqmqk52k56ghg5wp6323859brhl";
    };
  };
  "https://repo1.maven.org/maven2/org/javassist/javassist/3.18.1-GA/javassist-3.18.1-GA" =
  {
    host = repositories.maven;
    path =
      "org/javassist/javassist/3.18.1-GA/javassist-3.18.1-GA";
    type = "jar";
    pom = {
      sha1 = "af3b2b71de5691126a16d00e3155576dcaa1e3dc";
      sha256 = "03ysag9wb2binc8r7nkwhpsw97sdfhhg6isydba3apy4x1prbcas";
    };
    jar = {
      sha1 = "d9a09f7732226af26bf99f19e2cffe0ae219db5b";
      sha256 = "0qk19ja8zv4jdxcmw4krcdax1j4iham9gszmjc7vp66hmwqi5drz";
    };
  };
  "https://repo1.maven.org/maven2/org/jsoup/jsoup/1.9.2/jsoup-1.9.2" =
  {
    host = repositories.maven;
    path =
      "org/jsoup/jsoup/1.9.2/jsoup-1.9.2";
    type = "jar";
    pom = {
      sha1 = "72f6a64cd9cd47bb7aba05c84b9935650a098998";
      sha256 = "0zh9xn8qcgjyhki5kbhb3rhbhd12avwqy6n9fqfzymdq3c41k8lk";
    };
    jar = {
      sha1 = "5e3bda828a80c7a21dfbe2308d1755759c2fd7b4";
      sha256 = "0sm4s1a8plb8z5467799jvp0s37dr98q82z3y436w9c2n7qqa64w";
    };
  };
  "https://repo1.maven.org/maven2/org/kohsuke/pom/14/pom-14" =
  {
    host = repositories.maven;
    path =
      "org/kohsuke/pom/14/pom-14";
    type = "jar";
    pom = {
      sha1 = "7e52f77bc3cd74f323816fadbcb9303df219b1ea";
      sha256 = "10zfsgibpv357q5pmq1n8rbjp693xllzjgb553xqg2d5hky4a3qm";
    };
  };
  "https://repo1.maven.org/maven2/org/kohsuke/pom/6/pom-6" =
  {
    host = repositories.maven;
    path =
      "org/kohsuke/pom/6/pom-6";
    type = "jar";
    pom = {
      sha1 = "54ee53971ff8b4cb72d8287a11d5c6df6426c250";
      sha256 = "0fii56q9qqg6c20pivi403pr2nvdhgwpiv0c8cq01r1mq6g0dhx4";
    };
  };
  "https://repo1.maven.org/maven2/org/mozilla/rhino/1.7R5/rhino-1.7R5" =
  {
    host = repositories.maven;
    path =
      "org/mozilla/rhino/1.7R5/rhino-1.7R5";
    type = "jar";
    pom = {
      sha1 = "9aff149fb609ab85257cbf4dcff7bfc786df7321";
      sha256 = "0fyds54znn0hxd60aylfixal8xgw3vw07q28lb5drxa4mg38gjfv";
    };
    jar = {
      sha1 = "95f0003cea7ebf26aef5ed64c77c05fcd1ff9648";
      sha256 = "1h090k4f8idv3a5zsq4vn2d9x6mmal3jpm6qgphpfimw3akhj3p0";
    };
  };
  "https://repo1.maven.org/maven2/org/msgpack/msgpack/0.6.12/msgpack-0.6.12" =
  {
    host = repositories.maven;
    path =
      "org/msgpack/msgpack/0.6.12/msgpack-0.6.12";
    type = "jar";
    pom = {
      sha1 = "92138e8a6a64f25d226b6244f80dc22154d79fa7";
      sha256 = "1vkd0p2rb1pdxh963235mkczamqg05p17mdplmcq3ppq0a7psjcl";
    };
    jar = {
      sha1 = "6a0c88fe022993c490011c3dce7127b29f9a9b3b";
      sha256 = "0plvpp9ra9848sb3psx2yi0gvk5gm146hhnwln08wj10hmfsd770";
    };
  };
  "https://repo1.maven.org/maven2/org/ow2/asm/asm-all/4.2/asm-all-4.2" =
  {
    host = repositories.maven;
    path =
      "org/ow2/asm/asm-all/4.2/asm-all-4.2";
    type = "jar";
    pom = {
      sha1 = "7617be8df6235b6f36e2203b8d598a9c9361db4f";
      sha256 = "16wrb6rrkgagzymzcgalxic87ficq74ga8ymvk81ryrf0a1lrz54";
    };
    jar = {
      sha1 = "7f7277e5b8002226ebfc8b861c775da8f6a55afd";
      sha256 = "15kppkl7mwkp77irlbxvmjrgs74ggwbvs7kwsv4ad2dq3np9igvh";
    };
  };
  "https://repo1.maven.org/maven2/org/ow2/asm/asm-parent/4.2/asm-parent-4.2" =
  {
    host = repositories.maven;
    path =
      "org/ow2/asm/asm-parent/4.2/asm-parent-4.2";
    type = "jar";
    pom = {
      sha1 = "10baedb8215a42263be17a16707985bab3b33f9e";
      sha256 = "08jjay2ziyad97vbgyh8cb1pqnr8m8j109qmdaln2n3gnhcs4kqz";
    };
  };
  "https://repo1.maven.org/maven2/org/ow2/ow2/1.3/ow2-1.3" =
  {
    host = repositories.maven;
    path =
      "org/ow2/ow2/1.3/ow2-1.3";
    type = "jar";
    pom = {
      sha1 = "f679d6639bfb209b0836a5e7cf09bfbcc1a41f06";
      sha256 = "1yr8hfx8gffpppa4ii6cvrsq029a6x8hzy7nsavxhs60s9kmq8ai";
    };
  };
  "https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/4/oss-parent-4" =
  {
    host = repositories.maven;
    path =
      "org/sonatype/oss/oss-parent/4/oss-parent-4";
    type = "jar";
    pom = {
      sha1 = "281323f0e2b10184d6c6b230909401166b437e01";
      sha256 = "1vh6hjqq03hpwqvx7kf4lnzg2avvjf4narns9wyj3n8ry1f9j4y5";
    };
  };
  "https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/5/oss-parent-5" =
  {
    host = repositories.maven;
    path =
      "org/sonatype/oss/oss-parent/5/oss-parent-5";
    type = "jar";
    pom = {
      sha1 = "3ae20880ad3d5da6b1caec19e3de7e70dd2dd762";
      sha256 = "0g8da9zsimg7drhsnzivb2c874jda96frbii05iqlpaq189d8y0n";
    };
  };
  "https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/7/oss-parent-7" =
  {
    host = repositories.maven;
    path =
      "org/sonatype/oss/oss-parent/7/oss-parent-7";
    type = "jar";
    pom = {
      sha1 = "46b8a785b60a2767095b8611613b58577e96d4c9";
      sha256 = "0m4lallnlhyfj3z24ispxzwvsxzaznhw6zsmk4j74sibr5kqh7xm";
    };
  };
  "https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9" =
  {
    host = repositories.maven;
    path =
      "org/sonatype/oss/oss-parent/9/oss-parent-9";
    type = "jar";
    pom = {
      sha1 = "e5cdc4d23b86d79c436f16fed20853284e868f65";
      sha256 = "0yl2hbwz2kn1hll1i00ddzn8f89bfdcjwdifz0pj2j15k1gjch7v";
    };
  };
}
