(ns legacy.status-im.keycard.keycard)

(defprotocol Keycard
  (start-nfc [this args])
  (stop-nfc [this args])
  (set-nfc-message [this args])
  (check-nfc-support [this args])
  (check-nfc-enabled [this args])
  (open-nfc-settings [this])
  (register-card-events [this args])
  (set-pairings [this args])
  (on-card-disconnected [this callback])
  (on-card-connected [this callback])
  (remove-event-listener [this event])
  (remove-event-listeners [this])
  (get-application-info [this args])
  (factory-reset [this args])
  (install-applet [this args])
  (install-cash-applet [this args])
  (init-card [this args])
  (install-applet-and-init-card [this args])
  (pair [this args])
  (generate-and-load-key [this args])
  (unblock-pin [this args])
  (verify-pin [this args])
  (change-pin [this args])
  (change-puk [this args])
  (change-pairing [this args])
  (unpair [this args])
  (delete [this args])
  (remove-key [this args])
  (remove-key-with-unpair [this args])
  (export-key [this args])
  (unpair-and-delete [this args])
  (import-keys [this args])
  (get-keys [this args])
  (sign [this args])
  (sign-typed-data [this args])
  (save-multiaccount-and-login [this args])
  (login [this args])
  (send-transaction-with-signature [this args])
  (delete-multiaccount-before-migration [this args]))
