import re

# To learn about Buck see [Docs](https://buckbuild.com/).
# To run your application with Buck:
# - install Buck
# - `npm start` - to start the packager
# - `cd android`
# - `cp ~/.android/debug.keystore keystores/debug.keystore`
# - `./gradlew :app:copyDownloadableDepsToLibs` - make all Gradle compile dependencies available to Buck
# - `buck install -r android/app` - compile, install and run application
#

lib_deps = []
create_aar_targets(glob(["libs/*.aar"]))
create_jar_targets(glob(["libs/*.jar"]))

android_library(
  name = 'all-libs',
  exported_deps = lib_deps
)

android_library(
  name = 'app-code',
  srcs = glob([
    'src/main/java/**/*.java',
  ]),
  deps = [
    ':all-libs',
    ':build_config',
    ':res',
  ],
)

android_build_config(
  name = 'build_config',
  package = 'im.status.ethereum',
)

android_resource(
  name = 'res',
  res = 'src/main/res',
  package = 'im.status.ethereum',
)

android_binary(
  name = 'app',
  package_type = 'debug',
  manifest = 'src/main/AndroidManifest.xml',
  keystore = '//android/keystores:debug',
  deps = [
    ':app-code',
  ],
)
