name: Zenhub integration branch
on:
  create:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: status-im/zenhub-automations@cee4ebba0e01f948d2e0a57bfd2d28d715fabdd2
        with:
          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
          ZENHUB_API_KEY: ${{ secrets.ZENHUB_TOKEN }}
          INPROG_COLUMN: Z2lkOi8vcmFwdG9yL1BpcGVsaW5lLzMyODI1Mg
          REVIEW_COLUMN: Z2lkOi8vcmFwdG9yL1BpcGVsaW5lLzIyNjk0MTA
