name: Zenhub integration branch
on:
  create:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: status-im/zenhub-automations@4f91130dbd1a915ad30ffff461be737747e104ee
        with:
          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
          ZENHUB_API_KEY: ${{ secrets.ZENHUB_TOKEN }}
          INPROG_COLUMN: Z2lkOi8vcmFwdG9yL1BpcGVsaW5lLzMyODI1Mg
          REVIEW_COLUMN: Z2lkOi8vcmFwdG9yL1BpcGVsaW5lLzIyNjk0MTA
